### DISCUSSION TITLE
Can you configure what directories panes use in a layout?

### DISCUSSION THREAD

**Discussion by brendonsoto** [zellij-org/zellij#1049] [Q&A] [answered]
Hi! I'm trying to create a layout that creates multiple tabs with 1-2 panes but each tab has its own root directory. For example, two tabs, A & B, with two panes in A starting at `$HOME` and the a pane in B in `$HOME/documents/`.

I've tried using the `command` portion of the config w/ `cd` but have not had success.
Here's an example using the tabs portion of the config. This just extends the base config.
```yaml
tabs:
  - name: "A"
    direction: Vertical
    parts:
      - direction: Horizontal
        run:
          command: {cmd: cd, args: ["$HOME/documents"]}
      - direction: Horizontal
```

I'm not sure if I'm missing something. I've re-read the docs, but I'm not sure if maybe there's more to this since running other commands through the config work fine.

**Comment by a-kenji** [comment, marked as answer]
Hey! Thanks for reaching out.

`cd` is a shell intrinsic command, that (afaik) always instantly returns.
So this is heavily dependent on the shell you are using, this is a working example for fish:

```
---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
tabs:
  - direction: Vertical
    run:
         command: {cmd: fish, args: ["-C", "cd $HOME/Documents && fish"]}

```
