### DISCUSSION TITLE
Unbind ctrl+h not working?

### DISCUSSION THREAD

**Discussion by Lilja** [zellij-org/zellij#1528] [Q&A] [answered]
I'm testing zellij out, as a vim user that uses splits alot, i use the keybindings `^w h` and `^w l` to navigate left and right between splits. Because zellij has a keybind for moving panes with `^h`, it will be triggered by `^w h`.

I don't really know the best solution to for this problem, but right now i'm testing to unbind `ctrl+h` in the zellij config, but it doesn't seem to work:

```yaml
keybinds:
    normal:
        - unbind: [ Ctrl: 'h' ]
        - unbind: [ Ctrl: 'p' ]
        - unbind: [ Ctrl: 'b' ]
        - action: [SwitchToMode: Pane,]
          key: [ Ctrl: 'b' ]
    pane:
        - unbind: [ Ctrl: 'p' ]
        - unbind: [ Ctrl: 'b' ]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'b', Char: "\n", Char: ' ', Esc]
```

I seem to be able to unbind ctrl+p, but not ctrl+h. Am I doing something wrong?

Also, feel free to comment out different solutions that unbinding the key. Could I miss something in my workflow instead?
