### DISCUSSION TITLE
is anyone getting excessive usage of memory

### DISCUSSION THREAD

**Discussion by tshepang** [zellij-org/zellij#1693] [General]
I just got zellij killed by oom killer. I've also seen it reach multiple-gb of usage. I think this happens because I tend to have lots of logs, but I expected them to get removed from ram since I can only go so far back.

Here is my config:
```yaml
copy_clipboard: primary
scroll_buffer_size: 10000
pane_frames: false
scrollback_editor: emacsclient --tty
keybinds:
  unbind: [Ctrl: 'g']
  normal:
    - action: [SwitchToMode: Locked]
      key: [Esc]
  locked:
    - action: [SwitchToMode: Normal]
      key: [Esc]
```
If no one is seeing this, I can open an issue (with some guidance on what is needed).

I use zellij 0.31.3.
