### DISCUSSION TITLE
Autostart Zellij with Nushell in WSL

### DISCUSSION THREAD

**Discussion by valerii15298** [zellij-org/zellij#2414] [Q&A]
I am using Alacritty with windows WSL(`ubuntu2204.exe`)
With this `alacritty.yml` I am able to start `ubuntu2204.exe` when I open alacritty:
```yaml
shell:
  program: ubuntu2204.exe
```
But then it opens *bash* as default ubuntu terminal.
Is there a way to start **zellij** on ubuntu startup?
And when starting zellij start it with nushell(like this: `zellij options --default-shell nu`).
So that I do not need on every start run the command above.

**Comment by milespossing** [comment]
Some of this is more related to alacritty and wsl, but I managed to get nu running automatically. I'm working on the same thing you are:

```yaml
shell:
    program: wsl.exe
    args:
    - cd $HOME
    - "&&"
    - nu
```

I'll post back again if I get zellij working on nu load as well.

**Reply by milespossing** [reply]
@valerii15298, well it was actually easy. You can find the description [here](https://www.grailbox.com/2023/07/autostart-zellij-in-nushell/) but the basics are to just add the following to your nushell config file:

```nu
# zellij
def start_zellij [] {
  if 'ZELLIJ' not-in ($env | columns) {
    if 'ZELLIJ_AUTO_ATTACH' in ($env | columns) and $env.ZELLIJ_AUTO_ATTACH == 'true' {
      zellij attach -c
    } else {
      zellij
    }

    if 'ZELLIJ_AUTO_EXIT' in ($env | columns) and $env.ZELLIJ_AUTO_EXIT == 'true' {
      exit
    }
  }
}

start_zellij
```

EDIT:

I noticed that there was a bit of an issue where zellij was using zsh instead of nu. Annoying, but not an issue, I changed my alacritty startup script to the following (in doing this, I'm not sure that there is a need for the above script):

```yaml
shell:
    program: wsl.exe
    args:
    - cd $HOME
    - "&&"
    - zellij
    - options --default-shell nu
```
