### ISSUE TITLE
per-pane titlebar/footerbar?

### ISSUE THREAD

**Issue by colemickens** [zellij-org/zellij#1039]
Hi! I'm experimenting with zellij layouts for medium-length-ish semi-interactive running tasks that I want to fire up and be able to monitor at a glance.

Maybe there's another obvious way I'm thinking of, but I'd like to be able to set a title for the zellij **pane** or have it show the running command, etc. Maybe with an escape sequence (idk, not a terminal guy, etc).

**Comment by a-kenji** [comment]
Hi! Thanks for taking the time writing this issue!

In case you are writing layouts, you can use the following layout as a starting point:

```
tabs:
  - direction: Vertical
    name: "tab one"
    parts:
      - direction: Horizontal
        parts:
          - direction: Vertical
          - direction: Vertical
      - direction: Horizontal
  - direction: Vertical
    name: "this is the 2nd tab"
    parts:
      - direction: Horizontal
        parts:
          - direction: Vertical
            pane_name: "this is a named pane" 
          - direction: Vertical
      - direction: Horizontal
```
![image](https://user-images.githubusercontent.com/65275785/152838562-3cb848c2-57b5-4381-ad00-296667b1fa07.png)

You can also manually give the pane a name, in the default configuration that would be:
```
[Ctrl-p] - c - rename - [Enter]
```

If you configure your shell to report it's title, zellij will also set the pane name according to the title the shell reports. That can be a program, the current working directory, a git command. If you set the title manually that has precedence over the reported title by the shell.

For example I use part of my shell prompt as the title and modify the prompt once in zellij:
![image](https://user-images.githubusercontent.com/65275785/152839828-5bc99c37-2469-4520-98c1-5e9a02c7eef1.png)
![image](https://user-images.githubusercontent.com/65275785/152839963-d113afbe-1ccb-47ec-9df4-979676e65e12.png)

I hope that answers most of your questions! 
We do want to make information for pane frames more configurable in general and we do want to be able to support some sort of footerbar in the future.

**Comment by colemickens** [comment]
Is it possible that I have to do something in global config for this to work? It seems like plugins aren't active when I load with `--layout-path` ?

**Comment by a-kenji** [comment]
I just gave you the tabs part of the layout, here it would be the tabs together with the default layout:

```
---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 2
      run:
        plugin:
          location: "zellij:status-bar"
tabs:
  - direction: Vertical
    name: "tab one"
    parts:
      - direction: Horizontal
        parts:
          - direction: Vertical
          - direction: Vertical
      - direction: Horizontal
  - direction: Vertical
    name: "this is the 2nd tab"
    parts:
      - direction: Horizontal
        parts:
          - direction: Vertical
            pane_name: "this is a named pane"
          - direction: Vertical
      - direction: Horizontal
```


And here with a slightly different layout:
```
---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
tabs:
  - direction: Vertical
    name: "tab one"
    parts:
      - direction: Horizontal
        parts:
          - direction: Vertical
          - direction: Vertical
      - direction: Horizontal
  - direction: Vertical
    name: "this is the 2nd tab"
    parts:
      - direction: Horizontal
        parts:
          - direction: Vertical
            pane_name: "this is a named pane"
          - direction: Vertical
      - direction: Horizontal
```

So in short when opening a layout that doesn't load plugins they are not loaded.
It is planned that in the future on an unspecified layout the default layout will be loaded.
