### ISSUE TITLE
Remap quick increase/decrease size

### ISSUE THREAD

**Issue by RilDev** [zellij-org/zellij#1053]
I would like to remap the quick [Alt +] and [Alt -] keybindings to [Alt Up] and [Alt Down].

![image](https://user-images.githubusercontent.com/13135150/153375886-3c4ebc7f-f5db-44a3-a478-7141b6b75d5d.png)

But I can't find it in the `config.yaml` file.

Do you know where I could find it?

**Comment by a-kenji** [comment]
Hey! Thank you for reaching out!

You can see the current default `config.yaml` file with: `zellij setup --dump-config`

There you can find the keybinds:

```
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
```

Please don't hesitate reaching out in the future!

**Comment by RilDev** [comment]
Hi @a-kenji, thank you for the help!

I finally got around to try changing my `zellij` configuration and I have an issue:
```yaml
- action: [Resize: Increase,]
  key: [ Up,]
- action: [Resize: Decrease,]
  key: [ Down,]
```
Works fine, but
```yaml
- action: [Resize: Increase,]
  key: [ Alt: Up,]
- action: [Resize: Decrease,]
  key: [ Alt: Down,]
```
gives me an error: `Deserialization error: keybinds: data did not match any variant of untagged enum KeyActionUnbind at line 3 column 11`

Here is my full configuration:
```yaml
---
keybinds:
    unbind: true
    normal:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's',]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [NewPane: ]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        # Buggy remapping START
        - action: [Resize: Increase,]
          key: [ Alt: Up,]
        - action: [Resize: Decrease,]
          key: [ Alt: Down,]
        # Buggy remapping END

    locked:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'g',]
    resize:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'r', Char: "\n", Char: ' ',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [Quit]
          key: [Ctrl: 'q']
        - action: [Resize: Left,]
          key: [Char: 'h', Left,]
        - action: [Resize: Down,]
          key: [Char: 'j', Down,]
        - action: [Resize: Up,]
          key: [Char: 'k', Up, ]
        - action: [Resize: Right,]
          key: [Char: 'l', Right,]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
    pane:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'p', Char: "\n", Char: ' ',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [MoveFocus: Left,]
          key: [ Char: 'h', Left,]
        - action: [MoveFocus: Right,]
          key: [ Char: 'l', Right,]
        - action: [MoveFocus: Down,]
          key: [ Char: 'j', Down,]
        - action: [MoveFocus: Up,]
          key: [ Char: 'k', Up,]
        - action: [SwitchFocus,]
          key: [Char: 'p']
        - action: [NewPane: ,]
          key: [Char: 'n', Alt: 'n',]
        - action: [NewPane: Down,]
          key: [Char: 'd',]
        - action: [NewPane: Right,]
          key: [Char: 'r',]
        - action: [CloseFocus,]
          key: [Char: 'x',]
        - action: [ToggleFocusFullscreen,]
          key: [Char: 'f',]
        - action: [TogglePaneFrames,]
          key: [Char: 'z',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
    tab:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 't', Char: "\n", Char: ' ',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
          key: [Char: 'r']
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [GoToPreviousTab,]
          key: [ Char: 'h', Left, Up, Char: 'k',]
        - action: [GoToNextTab,]
          key: [ Char: 'l', Right,Down, Char: 'j']
        - action: [NewTab: ,]
          key: [ Char: 'n',]
        - action: [CloseTab,]
          key: [ Char: 'x',]
        - action: [ToggleActiveSyncTab]
          key: [Char: 's']
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [GoToTab: 1,]
          key: [ Char: '1',]
        - action: [GoToTab: 2,]
          key: [ Char: '2',]
        - action: [GoToTab: 3,]
          key: [ Char: '3',]
        - action: [GoToTab: 4,]
          key: [ Char: '4',]
        - action: [GoToTab: 5,]
          key: [ Char: '5',]
        - action: [GoToTab: 6,]
          key: [ Char: '6',]
        - action: [GoToTab: 7,]
          key: [ Char: '7',]
        - action: [GoToTab: 8,]
          key: [ Char: '8',]
        - action: [GoToTab: 9,]
          key: [ Char: '9',]
        - action: [ToggleTab]
          key: [ Char: "\t" ]
    scroll:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'r', Ctrl: 's', Char: ' ', Char: "\n",]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [ScrollToBottom, SwitchToMode: Normal,]
          key: [Ctrl: 'c',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [ScrollDown,]
          key: [Char: 'j', Down,]
        - action: [ScrollUp,]
          key: [Char: 'k', Up,]
        - action: [PageScrollDown,]
          key: [Ctrl: 'f', PageDown, Right, Char: 'l',]
        - action: [PageScrollUp,]
          key: [Ctrl: 'b', PageUp, Left, Char: 'h',]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
    renametab:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'r', Ctrl: 's', Char: ' ',]
        - action: [SwitchToMode: Tab,]
          key: [Char: "\n",]
        - action: [TabNameInput: [27] , SwitchToMode: Tab,]
          key: [Esc,]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
    session:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'o', Char: "\n", Char: ' ',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [Detach,]
          key: [Char: 'd',]

# Choose what to do when zellij receives SIGTERM, SIGINT, SIGQUIT or SIGHUP
# eg. when terminal window with an active zellij session is closed
# Options:
#   - detach (Default)
#   - quit
#on_force_close: quit
pane_frames: false
theme: tokyo-night-storm
themes:
  tokyo-night:
    fg: [169,177,214] #A9B1D6
    bg: [26,27,38] #1A1B26
    gray: [86,95,137] #565F89
    black: [65,72,104] #414868
    red: [247,118,142] #F7768E
    green: [158,206,106]  #9ECE6A
    yellow: [224,175,104] #E0AF68
    blue: [122,162,247]  #7AA2F7
    magenta: [187,154,247] #BB9AF7
    cyan: [42,195,222] #2AC3DE
    white: [192,202,245] #C0CAF5
    orange: [255,158,100] #FF9E64
  tokyo-night-storm:
    fg: [169,177,214] #A9B1D6
    bg: [36,40,59] #24283B
    gray: [86,95,137] #565F89
    black: [65,72,104] #414868
    red: [247,118,142] #F7768E
    green: [158,206,106]  #9ECE6A
    yellow: [224,175,104] #E0AF68
    blue: [122,162,247]  #7AA2F7
    magenta: [187,154,247] #BB9AF7
    cyan: [42,195,222] #2AC3DE
    white: [192,202,245] #C0CAF5
    orange: [255,158,100] #FF9E64
  tokyo-night-light:
    fg: [52,59,88] #343B58
    bg: [213,214,219] #D5D6DB
    gray: [150,153,163] #9699A3
    black: [15,15,20] #0F0F14
    red: [140,67,81] #8C4351
    green: [72,94,48]  #485E30
    yellow: [143,94,21] #8F5E15
    blue: [52,84,138]  #34548A
    magenta: [90,74,120] #5A4A78
    cyan: [15,75,110] #0F4B6E
    white: [52,59,88] #343B58
    orange: [150,80,39] #965027
```

Do you know how I could fix it?

Thanks!
