### ISSUE TITLE
Support for IDE-style layout

### ISSUE THREAD

**Issue by neo97dev** [zellij-org/zellij#1054]
Zellij combined with an editor like [Helix](https://helix-editor.com/) has great potential to replace IDEs like VSCode and others.
I would love to see a plugin that creates a VSCode-like interface within Zellij.

The basics of this would be:
- Persistent file browser (Strider) on the left pane with global state (switching tabs shouldn't change the file browser)
- Opening a file from Strider should optionally create a new tab instead of a new pane. (Maybe a different keybind for "open in new tab")
- Communication with Helix to know if the file has unsaved changes. If there are no changes, replace the file in that pane instead of opening a new tab/pane

**Comment by jaeheonji** [comment]
> Persistent file browser (Strider) on the left pane with global state (switching tabs shouldn't change the file browser)

It is still possible today by changing the layout configuration like this:
```yaml
---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
    - direction: Vertical
      parts:
        - direction: Horizontal
          split_size:
            Percent: 20
          run:
            plugin:
              location: "zellij:strider"
        - direction: Horizontal
          body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 2
      run:
        plugin:
          location: "zellij:status-bar"
tabs:
  - direction: Vertical
```

> Opening a file from Strider should optionally create a new tab instead of a new pane. (Maybe a different keybind for "open in new tab")

Yes right, It is pretty good options, and it is possible. (If you are interested in implementing this feature, you can contribute freely 😄)

> Communication with Helix to know if the file has unsaved changes. If there are no changes, replace the file in that pane instead of opening a new tab/pane

I think this is also a good idea. And I think this can be applied not only to `Helix` but also to other editors. (maybe, by saving the status of which file is currently open in which tab..?)
