### ISSUE TITLE
Run multiple commands in layouts

### ISSUE THREAD

**Issue by Korbeil** [zellij-org/zellij#1099]
Hey,

I would like to create layout for my projects but to do that I need to run multiple commands.
For example here is a script I'm running when starting a project:
```bash
cd ~/path/to/my/project/
pipenv run fab create_database
pipenv shell
```

First part could be removed if we add a `cwd` configuration in the layout parts section.
For the 2 last lines I would need to run multiple commands, do you think that is possible ?

Thanks for the awesome tool :)

**Comment by Korbeil** [comment]
> Hey! Thanks for creating this issue! Yes, that is possible.
> 
> [zellij.dev/documentation/layouts.html](https://zellij.dev/documentation/layouts.html)

I did not find how to run multiple commands or setting a cwd here, could you give me an example maybe ?

**Comment by welcoMattic** [comment]
@a-kenji I've just tested, and it doesn't work, neither with `zsh`. Is it feasible to pass a full string command like:

```yaml
---
tabs:
  - name: Application
    run:
      command: "cd /tmp && exec bash"
```

And it will be up to zellij to encapsulate it with the current shell "`-c`" option?

**Comment by a-kenji** [comment]
I tested it now and it does work for both bash and zsh for me.

```
---
tabs:
  - name: tab 1
    run:
      command: {cmd: bash, args: ["-c", "cd /tmp && exec bash"]}
```

Is there more information that you can maybe give me where it fails.
Does it show an error?
Can you run the arguments when you put them in a script and run it then?

> And it will be up to zellij to encapsulate it with the current shell "-c" option?

Maybe? I do want to have the ergonomics of the command improved. Especially on holding a pane open. I am not sure how feasible it is to integrate behavior that is very shell dependent.

**Comment by a-kenji** [comment]
@welcoMattic 

Just to make sure, did you have the arguments split like this:
```
["-c", "cd /tmp && exec bash"]
```
?

**Comment by welcoMattic** [comment]
@a-kenji Yes, I have args splitted. But there are 2 things:

1. `command: {cmd: bash, args: ["-c", "cd /tmp && exec bash"]}` works, I have a zellij instance, with `bash` in a pane.
2. command: {cmd: bash, args: ["-c", "cd /tmp && ls"]} doesn't work, I have instantly `Bye from Zellij!`

What is needed here, is to execute some command to prepare a pane for a project (installing dependancies, running containers, etc).

**Comment by a-kenji** [comment]
Does this work:
```
tabs:
  - name: tab 1
    run:
      command: {cmd: "bash", args: ["-c", "cd /tmp && ls && exec bash"]}
```
?
`ls` returns and we don't hold on a returning command yet. But you can work around it while keeping a command open.
