### ISSUE TITLE
Disable status-bar in config file not work

### ISSUE THREAD

**Issue by kaigedong** [zellij-org/zellij#1105]
Hi, I want to disable `status-bar`, but after I remove the configuration of this plugins, and restart zellij, it's still there.

My config is in `$HOME/.config/zellij/config.yaml`. And it works when I change the keybinding. 

I am using Manjaro, and install zellij by cargo.

```yaml
plugins:
    - path: tab-bar
      tag: tab-bar
    - path: strider
      tag: strider
    # - path: status-bar
    #   tag: status-bar
```

![11](https://user-images.githubusercontent.com/38344234/155445832-1418e8b6-f7d0-406a-a530-2e2fcca26d7d.png)
