### ISSUE TITLE
Selection characters are omitted 

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#1368]
**Basic information**

`zellij --version`: 0.29.0
`uname -av`: Linux 5.17.3 #1-NixOS SMP PREEMPT Wed Apr 13 17:27:43 UTC 2022 x86_64 GNU/Linux
`alacritty` : alacritty 0.10.1 () 

When selecting text with a mouse, it is correctly copied, but the selection characters are omitted.

**Comment by a-kenji** [comment]
I update the issue with a screenshot.

**Comment by tlinford** [comment]
Do you mean that the selection doesn't become highlighted?

**Comment by a-kenji** [comment]
@tlinford,
Yes, exactly!

**Comment by tlinford** [comment]
Hmm, working alright for me. Maybe something theme/color related?

**Comment by a-kenji** [comment]
@tlinford,
You are right, it is theme/color related. Weird.
The colors in my config didn't change at all.
I'll update the issue with the theme.

**Comment by tranzystorek-io** [comment]
Same on 0.31.3 with the dracula theme:

```yaml
themes:
  dracula:
    fg: [248, 248, 242]
    bg: [40, 42, 54]
    black: [0, 0, 0]
    gray: [68, 71, 90]
    red: [255, 85, 85]
    green: [80, 250, 123]
    yellow: [241, 250, 140]
    blue: [98, 114, 164]
    magenta: [255, 121, 198]
    cyan: [139, 233, 253]
    white: [255, 255, 255]
    orange: [255, 184, 108]
```

**Comment by BeLeap** [comment]
Changing bg to a different color worked for me.

```yaml
theme: gruvbox-dark

themes:
  gruvbox-dark:
    bg: [10, 10, 10] # Originally, bg: [40, 40, 40]
    red: [204, 36, 29]
    green: [152, 151, 26]
    yellow: [215, 153, 33]
    blue: [69, 133, 136]
    magenta: [177, 98, 134]
    orange: [214, 93, 14]
    fg: [213, 196, 161]
    cyan: [104, 157, 106]
    black: [60, 56, 54]
    white: [251, 241, 199]

```


<img width="1624" alt="스크린샷 2022-08-25 오전 8 36 00" src="https://user-images.githubusercontent.com/46488521/186541726-7bb2e852-6efd-483c-9650-9d1158ce88d5.png">

Maybe we should update example theme configurations.
