### ISSUE TITLE
Themes could be better documented, unclear if I have a bug

### ISSUE THREAD

**Issue by thor314** [zellij-org/zellij#1436]
I wanted to theme the green rectangle to another color; I assumed this was possible because of theme support, but themes only appear to change everything outside the green box. 

- It would be helpful if pictures of the themes were stored somewhere, so that users didn't have to open every one themselves
- Is there a way to change the green box to another color? 

Cheers, great application otherwise.

**Comment by a-kenji** [comment]
Thank you @thor314 for reaching out.
Can you elaborate please what you are trying to do?

This is how my theme looks like:

![image](https://user-images.githubusercontent.com/65275785/170474637-c081837d-18ed-4423-8c35-e2f1cb570cb0.png)

**Comment by thor314** [comment]
my config toml here: https://github.com/thor314/.files/blob/main/zellij/config.yaml

I've also tried launching with themes:
```sh
zellij options --theme zellij/example/themes/nord.yaml
```
Though the appearance usually only changes slightly, with small changes in the color/font of the tooltips at the top and bottom.
![image](https://user-images.githubusercontent.com/7041313/170495676-c471230c-09d0-4e38-bd73-89d4253110a2.png)

**Comment by a-kenji** [comment]
If you launch with `zellij options --theme tokyo-night` , it should launch with the theme. You can also put `theme: tokyo-night` in your configuration, then it will be sourced on start.

**Comment by thor314** [comment]
left: zellij options --theme tokyo-night
right:  zellij options --theme nord
Is this expected? There are slight differences like I mentioned, but the green color is constant 
![image](https://user-images.githubusercontent.com/7041313/170497266-be2244ef-7709-442d-9749-ba84d977356b.png)

**Comment by a-kenji** [comment]
It seems the theme authors decided to keep the green highlight then. You can change the green colour in your configuration.

**Comment by thor314** [comment]
After screwing around with it for another half hour, I discovered that I have to use the word `default` in my config, see below. I also discovered that the `zellij options --theme solarized-dark` style of specifying themes changes appearance much less than I would have expected. My fix looks like this:

From:
```
# changing these values WON'T CHANGE ANYTHING
themes:
   tokyo-night:
     fg: [169,177,214] #A9B1D6
     bg: [26,27,38] #1A1B26
     black: [56,62,90] #383E5A
     red: [249,51,87] #F9334D
     green: [158,206,106]  #9ECE6A
     yellow: [224,175,104] #E0AF68
     blue: [122,162,247]  #7AA2F7
     magenta: [187,154,247] #BB9AF7
     cyan: [42,195,222] #2AC3DE
     white: [192,202,245] #C0CAF5
     orange: [255,158,100] #FF9E64
```
To:
```
# changing these values will change things.
themes:
  default:
    fg: [169,177,214] #A9B1D6
    bg: [26,27,38] #1A1B26
    black: [56,62,90] #383E5A
    red: [249,51,87] #F9334D
    green: [18,26,16]  #9ECE6A
    yellow: [24,75,4] #E0AF68
    blue: [122,162,247]  #7AA2F7
    magenta: [187,154,247] #BB9AF7
    cyan: [42,195,222] #2AC3DE
    white: [192,202,245] #C0CAF5
    orange: [255,158,100] #FF9E64
```

**Comment by a-kenji** [comment]
Oh, it seemed to me that you got that from my earlier message, apologies.

https://zellij.dev/documentation/themes.html

Your conclusion is not quite correct, if I may quote myself from earlier:

> If you launch with `zellij options --theme tokyo-night` , it should launch with the theme. 

So running this command with your earlier configuration specifies the appropriate theme.

> You can also put theme: tokyo-night in your configuration, then it will be sourced on start.

An example of that would be:
```
theme: tokyo-night
themes:
   tokyo-night:
     fg: [169,177,214] #A9B1D6
     bg: [26,27,38] #1A1B26
     black: [56,62,90] #383E5A
     red: [249,51,87] #F9334D
     green: [158,206,106]  #9ECE6A
     yellow: [224,175,104] #E0AF68
     blue: [122,162,247]  #7AA2F7
     magenta: [187,154,247] #BB9AF7
     cyan: [42,195,222] #2AC3DE
     white: [192,202,245] #C0CAF5
     orange: [255,158,100] #FF9E64
```

So to summarize, you can put multiple themes in your configuration, and there are 3 ways to decide which one is picked: `default` theme, then `theme: [NAME]`, then `zellij options --theme [NAME]` with increasing override.
