### ISSUE TITLE
Support keybindings with Enter

### ISSUE THREAD

**Issue by nilscox** [zellij-org/zellij#1480]
Hello,

I am trying to add a keybinding to alt+enter, but I get an error when launching zellij:

```
Deserialization error: keybinds: data did not match any variant of untagged enum KeyActionUnbind at line 9 column 11
```

Here is the config I use:

```
keybinds:
    unbind: true
    normal:
        # ...
        - action: [ToggleFocusFullscreen,]
          key: [Alt: Enter]
```

As far as I understand, the "Enter" keyword isn't supported. Is there a way to bind a command to alt+enter?

`zellij --version`: `zellij 0.30.0`
`alacritty --version`: `alacritty 0.10.1 ()`

Let me know if you need any other information.
Thanks!
