### ISSUE TITLE
Can't create keybind to `Ctrl: "i"`

### ISSUE THREAD

**Issue by TornaxO7** [zellij-org/zellij#1609]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**Basic information**

`zellij --version`: `zellij 0.30.0`
`stty size`: `48 191`
`uname -av` or `ver`(Windows): `Linux TORNAX-ARCH 5.18.14-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 23 Jul 2022 11:46:17 +0000 x86_64 GNU/Linux`

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
```
kitty 0.25.2 created by Kovid Goyal
```

**Further information**
Reproduction steps, noticeable behavior, related issues, etc

Add the following keybiding:
```yaml
keybinds:
    unbind: true
    normal:
        - action: [SwitchToMode: locked]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Pane]
          key: [Ctrl: 'i']
```

and open up `zellij` and press `Ctrl + i`. Nothing happens but I expected to be in the `pane` mode.

Here's my full `~/.config/zellij/config.yaml` if you need it:

<details>

```yaml
pane_frames: false
theme: solarized-light
copy_command: "xclip -selection clipboard"
scrollback_editor: nvim

keybinds:
    unbind: true
    normal:
        - action: [SwitchToMode: locked]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Pane]
          key: [Ctrl: 'i']
        - action: [SwitchToMode: Resize]
          key: [Ctrl: 'r']
        - action: [SwitchToMode: Tab]
          key: [Ctrl: 't']
        - action: [SwitchToMode: Session]
          key: [Ctrl: 's']
        - action: [NewPane:]
          key: [Ctrl: 'n']
        - action: [MoveFocusOrTab: Left]
          key: [Ctrl: 'h']
        - action: [MoveFocusOrTab: Right]
          key: [Ctrl: 'l']
        - action: [MoveFocus: Down]
          key: [Ctrl: 'j']
        - action: [MoveFocus: Up]
          key: [Ctrl: 'k']
        - action: [Detach]
          key: [Ctrl: 'q']
        # uncomment this and adjust key if using copy_on_select=false
        # - action: [Copy: ]
        #   key: [ Alt: 'c']
    locked:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'g',]
    tab:
        - action: [SwitchToMode: Normal]
          key: [Ctrl: 'g', 'Esc']
        - action: [NewTab: ]
          key: [Ctrl: 'n']
        - action: [GoToNextTab]
          key: [Ctrl: 'l']
        - action: [GoToPreviousTab]
          key: [Ctrl: 'h']
    pane:
      - action: [SwitchToMode: normal]
        key: [Ctrl: 'g']
      - action: [MoveFocus: Left,]
        key: [ Char: 'h', Left]
      - action: [MoveFocus: Right]
        key: [ Char: 'l', Right]
      - action: [MoveFocus: Down]
        key: [ Char: 'j', Down]
      - action: [MoveFocus: Up]
        key: [ Char: 'k', Up]

# plugins:
    # - path: tab-bar
    #   tag: tab-bar
    # - path: status-bar
    #   tag: status-bar
    # - path: strider
    #   tag: strider
    # - path: compact-bar
    #   tag: compact-bar

themes:
  solarized-light:
    bg: [253, 246, 227]
    red: [220, 50, 47]
    green: [133, 153, 0]
    yellow: [181, 137, 0]
    blue: [38, 139, 210]
    magenta: [211, 54, 130]
    orange: [203, 75, 22]
    fg: [101, 123, 131]
    cyan: [42, 161, 152]
    black: [7, 54, 66]
    white: [238, 232, 213]
```

</details>
