### ISSUE TITLE
Adding a short-lived run command to a layout file's `tabs` section prevents the tab from being shown

### ISSUE THREAD

**Issue by jjpe** [zellij-org/zellij#1635]
Thank you for taking the time to file this issue! Please follow the instructions and fill in the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

**Basic information**

`zellij --version`: **0.31.1**
`stty size`: **31 155**
`uname -av` or `ver`(Windows): **Linux lear 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux**

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`nvim --version`: NVIM v0.5.0-dev+1299-g1c2e504d5  (used the appimage release)
`alacritty --version`: alacritty 0.7.2 (5ac8060b)

alacritty: alacritty **0.10.1 ()**
nushell: **0.66.2**

**Further information**
Reproduction steps, noticeable behavior, related issues, etc

I have this in ~/.config/zellij/layout.yaml:
```yaml
--
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 2
      run:
        plugin:
          location: "zellij:status-bar"
tabs:
  - direction: Vertical
    name: "foo"
  - direction: Horizontal
    name: "baz"
    parts:
      - run:
          command: { cmd: echo, args: ["Do the thing!"] }

```
With the last run command  enabled like it is, when I start Zellij, the tab is technically shown, but it is deleted as soon as the `echo` completes, meaning it effectively shows up and no navigation is possible to it.
This is less than desirable, since in some of my tabs I effectively want to `cd` into a tab-specific directory.

Could a setting be added to make it configurable whether or not a tab is destroyed after completion of the command?

**Comment by a-kenji** [comment]
Thank you for reaching out. This is a duplicate of  #707.

In short: We do want this option.

Right now you can emulate this option, but this is shell dependent and not as ergonomic as one would like. A possible example is:

```
command:
	cmd: fish
	arg: [ "-C", "echo Do the thing!" ]
```

This also works with `cd`:
```
tabs:
  - run:
      command: 
        cmd: fish
        args: ["-C", "echo Do the thing!"]
  - run:
      command: 
        cmd: fish
        args: ["-C", "cd ~/.config/zellij/layouts"]
```
