### ISSUE TITLE
borderless not working

### ISSUE THREAD

**Issue by hgigas** [zellij-org/zellij#1647]
compact.yaml
```
---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      parts:
        - direction: Horizontal
          borderless: true
          split_size:
            Percent: 50
          run:
            plugin:
              location: "zellij:compact-bar"
        - direction: Horizontal
          borderless: true
          split_size:
            Percent: 50
          run:
            plugin:
              location: "zellij:status-bar"
```
Showing borders:

![zellij_borderless](https://user-images.githubusercontent.com/100573434/183888738-e1594a41-a16e-42a1-8805-20a807b5643c.png)

**Basic information**

`zellij --version`: 0.31.1
`uname -av`: Linux ... 5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux

`alacritty --version`: alacritty 0.7.2 (5ac8060b)
