### ISSUE TITLE
Checksums on Release page is incorrect

### ISSUE THREAD

**Issue by kaushalyap** [zellij-org/zellij#1685]
I checked `sha256` checksum for `zellij-x86_64-unknown-linux-musl` with `zellij-x86_64-unknown-linux-musl.sha256sum` using `sha256sum` command line tool, checksums did not match.

**Comment by tlinford** [comment]
did you check the binary or the .tar.gz file?
binary checks out for me.

```shell
~/Downloads/zellij
❯ cat zellij-x86_64-unknown-linux-musl.sha256sum
bfffe4d14eaf60e1542bac0a72cc83d239d541ad82b833a0a3b4e805492f7e2c  zellij

~/Downloads/zellij
❯ sha256sum zellij
bfffe4d14eaf60e1542bac0a72cc83d239d541ad82b833a0a3b4e805492f7e2c  zellij
```

**Comment by kaushalyap** [comment]
I checked the tar, I usually check the tar in other projects.

Anyway, binary checksum matched, so I'll close.

**Comment by taqtiqa-mark** [comment]
Please reopen. The default for tools such as Salt/Chef is the checksum relates to the artifact that downloaded.

**Comment by imsnif** [comment]
@taqtiqa-mark - is there a reference/best practice for this written somewhere that you can link to?

**Comment by taqtiqa-mark** [comment]
Search for `source_hash` or `hash` here for Salt [Salt](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.file.html)

Search for `checksum` here for [Chef](https://docs.chef.io/resources/remote_file/)

They also document where they support remote file holding the checksum/hash.

HTH?

**Comment by imsnif** [comment]
I did not find this specified in the links @taqtiqa-mark - but maybe I'm missing something?

I mainly want a resource that says this explicitly in one way or another. Or to see some reasoning for one way. Otherwise people with different expectations can open an issue to reverse this somewhere down the line.

**Comment by taqtiqa-mark** [comment]
They even give an example (Salt):

```
tomdroid-src-0.7.3.tar.gz:
  file.managed:
    - name: /tmp/tomdroid-src-0.7.3.tar.gz
    - source: https://launchpad.net/tomdroid/beta/0.7.3/+download/tomdroid-src-0.7.3.tar.gz
    - source_hash: 79eef25f9b0b2c642c62b7f737d4f53f
 ```
