### ISSUE TITLE
Zellij layout with session name called inside the session causes recoursive calamity

### ISSUE THREAD

**Issue by alekspickle** [zellij-org/zellij#1735]
**Basic information**

`zellij --version`: 0.31.4
`stty size`: 36 137
`uname -av` or `ver`(Windows): Linux pickle 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

`nvim --version`: NVIM v0.7.0 (appimage installation)
`alacritty --version`: alacritty 0.10.1

**Further information**
Have this layout in `~/.config/zellij/layouts/default.yaml`:
(I believe single `session` field is enough to reproduce, but just for the context I am providing my env)
```

---
session:
  name: "nevermind"
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:status-bar"
tabs:
  - direction: Vertical
    name: dev
  - direction: Vertical
    name: misc


```

Now if you do `zj` and run it again inside the session it obviously will try to attach session with such name and you see it doing just that but hundreds of times. After you close this calamity with Ctrl-C, zellij CLI is completely unresponsive until you do `killall zellij`.

I am not sure this should be handled at all, I just thought I let you know about this behavor.

Maybe there should be some command to fix such garbaged environments? Like `zellij clean`(inspired by `cargo clean`)
