### ISSUE TITLE
How to hide "interface locked" text?

### ISSUE THREAD

**Issue by z0al** [zellij-org/zellij#1742]
I want to auto-start zellij on every terminal session in locked mode by default but I'm bothered by the `-- INTERFACE LOCKED --` text. Is there any way to hide it without quitting Zellij?

Ideally, I'd want Zellij to stay out of the way when I'm not using it. 
![image](https://user-images.githubusercontent.com/12673605/191066133-1a5ab365-2e89-45f4-9692-017ffb534866.png)

I'm aiming for a minimalistic look and I want to use the presence of the tip as an indication that I'm not in a locked mode.

```yaml
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      pane_frames: false
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:status-bar"
```

![image](https://user-images.githubusercontent.com/12673605/191067088-f95aca96-d735-4e2f-85cc-886c32b068be.png)

Love Zellij btw, keep up the great work.

**Comment by har7an** [comment]
Hey @z0al,

at this point I'm afraid there is no way to hide the "LOCKED" mode indication. We're generally working towards a full rework of the whole plugin system, and we can try to incorporate this as a feature there, if you wish. However, we don't have any fixed date until which this will be implemented - it will likely take a while to get there.

In the meantime, you can build the status-bar plugin yourself and customize it entirely to your liking. After all, zellij allows for loading custom plugins. Would that be an option for you? I can guide you through the process, too, if you want.

**Comment by z0al** [comment]
Hey @har7an , thank you so much for your helpful response.

> In the meantime, you can build the status-bar plugin yourself and customize it entirely to your liking. After all, zellij allows for loading custom plugins

I guess building a plugin makes sense. I can give it a try. Could be a nice way to learn a bit of Rust :) 

Any links to docs or pieces of code to get started would be great. 

I will start by looking into reusing the existing status bar plugin code and make a few adjustments. Any tips are welcome.

Regardless, I think the argument for a custom plugin is fair enough, closing this issue.

**Comment by har7an** [comment]
Hi @z0al,

> I guess building a plugin makes sense. I can give it a try. Could be a nice way to learn a bit of Rust :)

It certainly is! Just keep in mind: You'll be responsible for keeping the plugin up-to-date when updating zellij in case errors/incompatibilities arise. So if you make an update and things break, maybe rebuild the plugin.

> Any links to docs or pieces of code to get started would be great.

Sure thing:

- If you only want to get rid of this particular text, just replace [this string here][1]
- If you also want to change the text for locked mode + floating panes, look [here][2] and [here][3]

> Regardless, I think the argument for a custom plugin is fair enough, the issue can be closed.

Glad to hear this may work for you! I'll keep the issue open until you've reported you got it working. Keep in mind that you'll also have to include your custom plugin in a layout file, like so:

```yaml
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 2
      run:
        plugin:
          location: "file:/home/you/somewhere/status-bar.wasm"
```

You should also install `cargo-make` and then run `cargo make wasm-opt-plugins` from the zellij root directory to build the plugins with optimizations. It will require a binary called `wasm-opt`, which you can grab from a release of [binaryen](https://github.com/WebAssembly/binaryen). The finished plugins reside in `assets/plugins/*.wasm`.

Feel free to ask in case things don't work as you expect. And happy hacking!


[1]: https://github.com/zellij-org/zellij/blob/2ae057d061db2dc4d41afe39cb40197d3d01c616/default-plugins/status-bar/src/second_line.rs#L48
[2]: https://github.com/zellij-org/zellij/blob/2ae057d061db2dc4d41afe39cb40197d3d01c616/default-plugins/status-bar/src/second_line.rs#L463
[3]: https://github.com/zellij-org/zellij/blob/2ae057d061db2dc4d41afe39cb40197d3d01c616/default-plugins/status-bar/src/second_line.rs#L498
