### ISSUE TITLE
Customize pane name and frame visibility in layouts yaml file

### ISSUE THREAD

**Issue by tqwewe** [zellij-org/zellij#1756]
Is it possible to configure the name of panes and their frame/border visibility on a per frame basis within a layout config file?

The file I'm working with is:
```yaml
---
---
template:
  direction: Horizontal
  parts:
    - direction: Vertical  # part 1
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
    - direction: Vertical # part 2
      body: true
    - direction: Vertical # part 3
      borderless: true
      split_size:
        Fixed: 2
      run:
        plugin:
          location: "zellij:status-bar"

tabs:
  - name: Main
    direction: Horizontal
    parts:
      - direction: Vertical
        # Cannot specify name or frame visibility here?
        run: 
          command: { cmd: hx, args: [] }
      - direction: Vertical
        # or here?
        focus: true
        split_size:
          Fixed: 20
```

**Comment by har7an** [comment]
Hey @tqwewe,

With the current config you can control the frame visibility (`borderless: true|false`), just refer to how the plugins are doing it:

```yaml
  parts:
    - direction: Vertical
      borderless: true     # <----
      split_size:
        Fixed: 1
```

As far as I'm aware you cannot name panes like this. We'll be switching the configuration format soon from YAML to KDL and naming panes in the config will be implemented there. So by the next release it should be possible.

**Comment by a-kenji** [comment]
Hi @tqwewe,
yes it it possible to set the pane name!

Just configure the panes in the following way:
```
  - run:
      command: 
        cmd: hx
    pane_name: heeeelix
```
