### ISSUE TITLE
Unwrap panick when closing panel

### ISSUE THREAD

**Issue by tqwewe** [zellij-org/zellij#1758]
**Basic information**

`zellij --version`: `0.31.4`
`stty size`: `66 256`
`uname -av` or `ver`(Windows): `Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64`

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`alacritty --version`: `alacritty 0.10.0`
`nu --version`: `nushell 0.68.1`

**Further information**
Reproduction steps:
1. Create a default layout in `~/.config/zellij/layouts/default.yaml` with the following content:
   <details>
        <summary>default.yaml</summary>

      ```yaml
      ---
      template:
        direction: Horizontal
        parts:
          - direction: Vertical
            borderless: true
            split_size:
              Fixed: 1
            run:
              plugin:
                location: "zellij:tab-bar"
          - direction: Vertical
            body: true
          - direction: Vertical
            borderless: true
            split_size:
              Fixed: 2
            run:
              plugin:
                location: "zellij:status-bar"

      tabs:
        - name: Main
          direction: Horizontal
          parts:
            - direction: Vertical
              focus: true
            - direction: Vertical
              split_size:
                Fixed: 20
      ```

   </details>
   
2. Start a normal zellij session.
3. Focus on the bottom panel, and press `Ctrl P X X` to close the panel.
4. See the error:
   > Error occurred in server:
   > 
   >  × Thread 'screen' panicked.
   >  ├─▶ Originating Thread(s)
   >  │   	1. stdin_handler_thread: AcceptInput
   >  │   	2. screen_thread: WriteCharacter
   >  │
   >  ├─▶ At /Users/ari/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.4/src/tab/mod.rs:1011:60
   >  ╰─▶ called `Option::unwrap()` on a `None` value
   >  help: If you are seeing this message, it means that something went wrong.
   >        Please report this error to the github issue.
   >        (https://github.com/zellij-org/zellij/issues)
