### ISSUE TITLE
layout converter creates invalid kdl with \" in command string

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1777]
https://github.com/zellij-org/zellij/pull/1759

I started a recent zellij build with my normal layout file, it convered it and blew up on me :)

The converter seems to unescape quotes, so a `"echo \"hi\""` in yaml becomes `"echo "hi""` in kdl.

Minimal repro:
`~/.config/zellij/layouts/test.yaml`:
```yaml
---
tabs:
  - direction: Vertical
    parts:
      - direction: Vertical
        run:
          command: {cmd: bash, args: ["-c", "exec bash --init-file <(echo \"echo hi\") -i"]}
```
The idea of the command is to drop you into an interactive shell that executed custom commands before. In this case it would just print `hi`.

`zellij --layout test`
```
  × Failed to parse Zellij configuration
   ╭─[.config/zellij/layouts/test:7:1]
 7 │             pane command="bash" {
 8 │                 args "-c" "exec bash --init-file <(echo "echo hi") -i"
   ·                 ────────────────────┬────────────────────
   ·                                     ╰── Failed to deserialize KDL node.
Possible reasons:
- Missing `;` after a node name, eg. { node; another_node; }
- Missing quotations (") around an argument node eg. { first_node "argument_node"; }
- Missing an equal sign (=) between node arguments on a title line. eg. argument="value"
- Found an extraneous equal sign (=) between node child arguments and their values. eg. { argument="value" }
 9 │             }
   ╰────
  help: For more information, please see our configuration guide: https://zellij.dev/documentation/configuration.html
```
The error message already shows that the escaped quotes were converted to normal ones.
