### ISSUE TITLE
keybinding `ctrl+j` does not work

### ISSUE THREAD

**Issue by Yangruipis** [zellij-org/zellij#1807]
## basic info

- version: `0.31.4`
- shell: `item2` + `zsh`

## reproducing

`config.yaml` is here

```yaml
keybinds:
    unbind: true
    normal:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'j',]    # use ctrl + j instead of ctrl + g
        ... # other config is the same as default
```

As the screenshot below shows,  when I press `ctrl+j`, I just get a new line in zsh, the keybinding is not captured.

Even though I unset the zsh keybings by **adding `bindkey -r "^J"` in my `.zshrc`**, it still doesn't work.

![image](https://user-images.githubusercontent.com/16623724/196369854-46e39773-d65f-41a2-9894-b3af5484702d.png)
