### ISSUE TITLE
Layout with multiple run commands on panes

### ISSUE THREAD

**Issue by sergiorgiraldo** [zellij-org/zellij#1809]
I have a layout with 3 panes, I want to have applications running by default with run:command directive. They dont work, they even do not render. This is my layout:

```
---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 2
      run:
        plugin:
          location: "zellij:status-bar"
tabs:
  - name: main
    focus: true
    direction: Horizontal
    parts:
    - direction: Horizontal
      split_size:
        Percent: 75
    - direction: Horizontal
      split_size:
        Percent: 25
  - name: todo+pomodoro+calendar
    direction: Vertical
    parts:
    - direction: Horizontal
      run:
        command: {cmd: mytd}
    - direction: Horizontal
      parts:
        - direction: Horizontal
          split_size:
            Percent: 70
          run:
            command: {cmd: pomo}
        - direction: Vertical
          split_size:
            Percent: 30
          run:
            command: {cmd: cal, args:["-3"]} #this does not work and this pane is not rendered.
            # if I remove the command, then it shows up.
  - name: processes
    direction: Vertical
    parts:
    - direction: Vertical
      split_size:
        Percent: 100
      run:
        command: {cmd: htop}
```
