### ISSUE TITLE
Wrong size with Maximized Alacritty

### ISSUE THREAD

**Issue by kontsaki** [zellij-org/zellij#2126]
Hello,

With Alacritty config 
```
shell:
  program: zellij
window:
  startup_mode: Maximized
```

Zellij starts in the wrong size

![Screenshot from 2023-01-31 19-24-29](https://user-images.githubusercontent.com/60739442/215849769-e0da1068-9c36-4369-b0de-185cc58c5fb1.png)

if I resize Alacritty then Zellij picks up the right size again

zellij 0.34.4
alacritty 0.11.0
Linux 6.0.12-76060006-generic #202212290932~1674139725~22.04~ca93ccf SMP PREEMPT_DYNAMIC Thu J x86_64 x86_64 x86_64 GNU/Linux
