### ISSUE TITLE
Allow zellij run CLI command to block until command has completed

### ISSUE THREAD

**Issue by blefevre** [zellij-org/zellij#3018]
The `zellij run` command should have the ability to block until the command being run has exited.

This would allow zellij to be invoked in scripts or shortcuts to perform actions and then have control returned to the caller.

For example, my use case is using Helix keybinds to invoke the Yazi file browser to select a file to which will then be opened in Helix. However currently I am unable to block until I've selected a file as the zellij command immediately exits.

**Comment by skariel** [comment]
+1. I need this feature to send text to the repl from Helix. See [here](https://github.com/helix-editor/helix/issues/2806#issuecomment-1551801413) how it's done for tmux

**Comment by rockboynton** [comment]
I have this working with Yazi specifically:

```toml
# config.toml
[keys.normal."'"]
y = ":sh zellij run --floating -n 'yazi picker' -- /home/rboynton/.config/fish/scripts/open_in_helix_from_yazi.fish"
```

```fish
set -l tmpfile /tmp/yazi-choice.txt
rm -f $tmpfile
yazi --chooser-file=$tmpfile
zellij action toggle-floating-panes
zellij action write 27 # send escape-key
zellij action write-chars ":open $(cat /tmp/yazi-choice.txt)"
zellij action write 13 # send enter-key
zellij action toggle-floating-panes
zellij action close-pane
```
