### ISSUE TITLE
Possibility to use alt+arrows in key bindings

### ISSUE THREAD

**Issue by jovandeginste** [zellij-org/zellij#351]
I tried to map alt+arrows to move between panes:

```yaml
keybinds:
  normal:
    - action: [MoveFocus: Left,]
      key: [ Alt: Left,]
```

But then zellij fails:

> There was an error in the config file:
Deserialisation error: keybinds: data did not match any variant of untagged enum KeyActionUnbind at line 2 column 9
