### ISSUE TITLE
Panes don't resize with terminal

### ISSUE THREAD

**Issue by Stoope** [zellij-org/zellij#354]
terminal - `alacritty`

layout.yaml
```
---
direction: Horizontal
parts:
  - direction: Vertical
    split_size:
      Fixed: 1
    plugin: tab-bar
  - direction: Vertical
    parts:
    - direction: Vertical
      split_size:
        Percent: 50
    - direction: Vertical
      split_size:
        Percent: 50
  - direction: Vertical
    split_size:
      Fixed: 2
    plugin: status-bar

```
MacOS 11.2.3
![Screen Recording ](https://user-images.githubusercontent.com/17287557/115951594-2ed5d400-a4ea-11eb-8811-86ac41efbf20.gif)
