### ISSUE TITLE
Configurable semantic escape characters for double-click selection

### ISSUE THREAD

**Issue by andre-ben** [zellij-org/zellij#4166]
Hi,

It would be great to have the possibility to configure which characters are treated as "word boundaries" during double-click selection, similar to Alacritty’s semantic_escape_chars option.

In Alacritty, this is configurable like this:

```yaml
selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
```

I attached a video showing an example: when double-clicking on a word enclosed in double quotes ("), I would like the selection to only include the word itself — excluding the double quotes.

https://github.com/user-attachments/assets/92c2d7c8-4075-4d8b-befe-f2203b8eb5c1

Having such an option would allow users to fine-tune how double-click selection behaves, especially for code, logs, or other structured text formats where the default word boundaries might not be ideal.

Thanks for considering!
