### ISSUE TITLE
nano editing yaml files behaves strange on RedHat systems

### ISSUE THREAD

**Issue by fansari** [zellij-org/zellij#462]
I have tested Zilly 0.7.0 editing yaml files with nano.

Editing the files (trying to go to the end of the file and back and edit) the cursor is jumping around leaving spaces and so on.

I could see the real content of the line by pressing "Ctrl-L".

Example: put this in a file line "main.yml" and edit this with nano on a RHEL/CentOS/Fedora system. In Debian I did not have this behaviour. Also nano behaves normal on RedHat systems running without Zellij. Tested with PuTTY and MobaXTerm.

```
- name: rsyslog
  block:
  - name: install rsyslog
    package:
      name: rsyslog
      state: present
```

Updating nano from  [ https://pkgs.dyn.su/el8/base/x86_64/nano-5.6.1-1.el8.x86_64.rpm](url) did not solve the issue.
