### ISSUE TITLE
Unable to create keybindinds for opening new tabs and switching tabs

### ISSUE THREAD

**Issue by matteematt** [zellij-org/zellij#483]
I am trying to configure zelliJ to use `Alt+t` to open a new tab, and `Alt+[0-9]` to jump to the tab of that number. I have created the following config to achieve this:

```yaml
keybinds:
  normal:
    - action: [GoToTab: 1]
      key: [Alt: 1]
    - action: [GoToTab: 2]
      key: [Alt: 2]
    - action: [GoToTab: 3]
      key: [Alt: 3]
    - action: [GoToTab: 4]
      key: [Alt: 4]
    - action: [GoToTab: 5]
      key: [Alt: 5]
    - action: [GoToTab: 6]
      key: [Alt: 6]
    - action: [GoToTab: 7]
      key: [Alt: 7]
    - action: [GoToTab: 8]
      key: [Alt: 8]
    - action: [GoToTab: 9]
      key: [Alt: 9]
    - action: [GoToTab: 0]
      key: [Alt: 0]
    - action: [NewTab]
      key: [Alt: t]
```
However these don't appear to work as I am expecting, they don't seem to do anything.
I have also added the exact same keybindings for the `pane` and `locked` modes too, and they don't seem to work either

I deleted my log file accidenally and now I am not sure how to get it to create a new one - I restarted zellij but it doens't seem to have created a new one

**Basic information**

`zellij --version`: zellij 0.7.0
`tput lines`: 60
`tput cols`:282
`uname -av` or `ver`(Windows): Darwin UKC02YDAXPJG5H 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

`alacritty --version`: alacritty 0.7.2 (5ac8060)

**Further information**
I did have a slightly unrelated issue with macs that they don't send `Alt` codes to terminals as expected. In some terminals there is a configuration option to make the operating system do so, but for Alacritty I had to find a hack on a github issue to send the alt codes for each character. I have tested this works though as it does make the default `Alt+n` and `Alt+hjkl` keybindings work. This is the relevent part of my alacritty config:
```yaml
key_bindings:
  - { key: N, mods: Alt, chars: "\x1bn"}
  - { key: H, mods: Alt, chars: "\x1bh"}
  - { key: J, mods: Alt, chars: "\x1bj"}
  - { key: K, mods: Alt, chars: "\x1bk"}
  - { key: L, mods: Alt, chars: "\x1bl"}
  - { key: T, mods: Alt, chars: "\x1bt"}
  - { key: 0, mods: Alt, chars: "\x1b0"}
  - { key: 1, mods: Alt, chars: "\x1b1"}
  - { key: 2, mods: Alt, chars: "\x1b2"}
  - { key: 3, mods: Alt, chars: "\x1b3"}
  - { key: 4, mods: Alt, chars: "\x1b4"}
  - { key: 5, mods: Alt, chars: "\x1b5"}
  - { key: 6, mods: Alt, chars: "\x1b6"}
  - { key: 7, mods: Alt, chars: "\x1b7"}
  - { key: 8, mods: Alt, chars: "\x1b8"}
  - { key: 9, mods: Alt, chars: "\x1b9"}
```
