### ISSUE TITLE
Hijacked CTRL+R (reverse-i-search) 😱😱😱

### ISSUE THREAD

**Issue by johschmitz** [zellij-org/zellij#532]
First of all very cool project! I absolutely love the focus on usability!

What I see as a bug or a huge design flaw though is that CTRL+R which everyone uses for reverse-i-search in various shells and also with fzf seems to have been hijacked!

How about remapping it to ALT+R or something different to avoid this major conflict? This should absolutely work in the default configuration because it is used heavily by many people.

In general conflicts with shell shortcuts should be avoided as much as possible.
All the remaining key mappings seem to be fine so far after 5-10 minutes testing. But maybe it makes sense to explicilty compare with the most important shortcuts of the most widely used shells.

**Comment by imsnif** [comment]
Hey, glad you like Zellij :)

While ctrl-r is the most widely collided of our shortcuts, I think we've since gotten complaints about every single one of them. This is honestly a very hard problem to solve. What we do right now is:

1. Allow users to lock the interface with ctrl + g when they want to send all shortcuts to the focused terminal
2. Allow users to configure the keybindings however they like: https://zellij.dev/documentation/keybindings.html

I don't think it would be easy to find a set of keys that would be great out of the box for everyone (eg. mac doesn't have an `Alt` key, so having one of the core modes bound to it is not ideal), but I've been thinking lately that maybe we should make an exception for ctrl-r specifically as you mentioned.

**Comment by johschmitz** [comment]
I fully agree that in general this is a hard or impossible to solve problem
and the locking idea seems to be an acceptable solution.

I also believe that you should definitely "make an exception" for CTRL+R.
Not because this is my personal preference but this function is just needed
to often and hence the current approach is not a sensible default for that
particular shortcut. Thanks for considering it and trying to find a good
compromise and sensible default for every user!

**Comment by nnovikov** [comment]
Is it possible to create prefix for hotkeys (like screen/tmux ctrl-a/ctrl-b)?

**Comment by imsnif** [comment]
> Is it possible to create prefix for hotkeys (like screen/tmux ctrl-a/ctrl-b)?

Kind of. This is essentially what locked mode does. You could configure Zellij to start in locked mode and then change the shortcuts to open the other modes to remove the ctrl.

**Comment by nnovikov** [comment]
Locked mode has different behavior: 
1. with prefix key I don't need use ctrl with r
2. mode will be auto unlocked after using
Prefix key is more convenient for me.

**Comment by imsnif** [comment]
AFAIK you should be able to build a config that does this: https://zellij.dev/documentation/keybindings.html

**Comment by johschmitz** [comment]
I think this discussion is now moving into a matter of taste direction. Personally I am open for any improvements that lowers the overall number of keypresses and is not too confusing.

With this being said, the main point of this issue is to suggest some sensible basic setup for the most important features that is easy to use for non-power users without reading the manual. And I absolutely do consider CTRL+R based search a very basic and very important shell feature. So let us maybe open a different issue for a more in depth discussion of general workflow improvements and focus on the CTRL+R issue in this issue.

**Comment by a-kenji** [comment]
@nnovikov 
This is a very basic configuration that could emulate a prefix-key:

```
---
default_mode: locked
keybinds:
    normal:
      - unbind: true
      - action: [SwitchToMode: Locked,]
        key: [Char: 'g',]
      - action: [SwitchToMode: Pane,]
        key: [Char: 'p',]
      - action: [SwitchToMode: Resize,]
        key: [Char: 'r',]
      - action: [SwitchToMode: Tab,]
        key: [Char: 't',]
      - action: [SwitchToMode: Scroll,]
        key: [Char: 's',]
      - action: [Quit,]
        key: [Char: 'q',]
    locked:
      - action: [SwitchToMode: Normal,]
        key: [Ctrl: 'g',]
    resize:
      - action: [SwitchToMode: Locked,]
        key: [Ctrl: 'g', Char: "\n", Char: ' ',]
    pane:
      - action: [SwitchToMode: Locked,]
        key: [Ctrl: 'g', Char: "\n", Char: ' ',]
    tab:
      - action: [SwitchToMode: Locked,]
        key: [Ctrl: 'g', Ctrl: 't', Char: "\n", Char: ' ',]
    scroll:
      - action: [SwitchToMode: Locked,]
        key: [Ctrl: 'g', Ctrl: 's', Char: ' ',
        Char: "\n",]
    renametab:
      - action: [SwitchToMode: Locked,]
        key: [Ctrl: 'g', Ctrl: 's', Char: ' ',]
```
