### ISSUE TITLE
Allow the layout config file to also start processes in each tab

### ISSUE THREAD

**Issue by stratosgear** [zellij-org/zellij#551]
Hopefully, this is not a duplicate request (searched but could find anything).

A useful feature, that we always use with multiplexers like tmux (through [tmuxp](https://github.com/tmux-python/tmuxp) and/or [tmuxinator](https://github.com/tmuxinator/tmuxinator)) is the ability to also autostart arbitrary processes associated with the panes, in the layout file.

Another essential config param would be the addition of a root path, under which any new terminals open (so the layout can contain a hardcoded path of the root of all terminals opened).  Maybe this is another issue?

So something like this in the config file would be extra handy:

```
---
root: ~/project1               <--- Add config param
direction: Horizontal
parts:
  - direction: Vertical
    split_size:
      Fixed: 1
    plugin: tab-bar
  - direction: Vertical
    command: startProcess1.sh   <--- Add config param
  - direction: Vertical
    split_size:
      Fixed: 2
    plugin: status-bar
    
```

**Comment by imsnif** [comment]
I think @a-kenji is doing some work on the `command` part, right?

**Comment by a-kenji** [comment]
Tank you for taking the time opening this issue!
This seems related to #284.

Yes, I am starting to look into how to add running commands in the layout,
but I suspect there will be quite some time until it can be implemented in a
clean way. I hope to get a very rough draft up in the next week.
Especially I am not sure about the error handling situation, this is again something
where some sort of ui to inform the user would be quite nice.

I think allowing the layout file to expand to tabs would be an awesome addition.
If anyone has good input on how that could be possible that would be great.

The root path is a good idea! Would you like to open a separate issue for that?

**Comment by dantepippi** [comment]
Hey @a-kenji  I was wondering if this would be a good candidate for an "executor plugin" in order to allow a better control of execution, store exit status, time running, etc. What do you think? Maybe an overkill.

**Comment by a-kenji** [comment]
Hey @dantepippi that is a pretty cool idea, if it is overkill it probably is a good place for a plugin. 

We want some of the basic functionality in the base layout system tough. And currently it is not possible to write such a plugin because we can't run arbitrary commands through the plugin system yet - which is one of the most limiting factors for plugins currently, so I hope that will be resolved somewhere in the future.

**Comment by stratosgear** [comment]
Probably I am missing some of the advanced features that you are planning/envisioning, but couldn't this be as simple as spawning a command in a bash shell like a user would have executed it if they had opened a terminal window on their own?

I mean do you really want to go that deep implementing all that extra functionality?  I would NOT expect zellij to do anything else apart from opening some terminal windows for me! 

What am I missing?

**Comment by a-kenji** [comment]
@stratosgear 
I am not sure If you are missing some features, or I am not understanding everything clearly,
either way thank you for the input! 

You are right, the spawning of commands in panes from the layout config file
should be relatively straight forward.
I am still stuck in some details currently,
but that should not be the biggest problem.

This is for a single tab.

In order to expand the layout to spawn multiple tabs, the layout system itself needs
to be adjusted in a way that is currently not obvious to me, any input here from anyone is 
greatly appreciated!

The `status-bar` and the `tab-bar` currently are default plugins that are loaded while loading
the `default.yaml` layout. They are persistent on each tab currently and we (probably?) want
to keep it that way for now. So when creating a new tab with a layout file - how do we inherit
the pinned plugins from the first tab? Does one tab need to be special when creating the layout,
and the other layouts inherit from that tab? Do we need to tell the plugins on which tabs
they should show up? Do we inherit until a conflicting pinned plugin is loaded in a new tab?
Do we error there, or load the more recent layout?

I would like to be able to describe such a layout in the future, but I don't know which solution
would have the least draw-backs yet.

**Comment by imsnif** [comment]
@a-kenji - what do you think of something like this?

```
direction: Horizontal
parts:
  - direction: Vertical
    split_size:
      Fixed: 1
    plugin: tab-bar
  - direction: Vertical
    tabs:
      - <layout_for_tab1> (or empty/tabname/null/some-more-intuitive-indication to just have one terminal in this tab)
      - <layout_for_tab2>
  - direction: Vertical
    split_size:
      Fixed: 2
    plugin: status-bar
```
(we'll have to validate that there's only one "tabs" section in a layout file)
