### ISSUE TITLE
Add default color themes

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#562]
Add default color themes.

Possibly even support for [base16](https://github.com/chriskempson/base16).

**Comment by casonadams** [comment]
Why not just have the terminal determine the theme.  As an example if using [alacritty](https://github.com/alacritty/alacritty).  Alacritty lets one index colour16 (orange) and colour18 (darkgray).  [base16-alacritty](https://github.com/aarowill/base16-alacritty) contains `256` color themes that use 16 (orange) and 18 (darkgray) already out of the box.  See the example below.

## alacritty.yml

```yml
schemes:
  tomorrow_dark: &tomorrow_dark
    # Default colors
    primary:
      background: "0x1d1f21"
      foreground: "0xc5c8c6"

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: "0x1d1f21"
      cursor: "0xc5c8c6"

    # Normal colors
    normal:
      black: "0x1d1f21"
      red: "0xcc6666"
      green: "0xb5bd68"
      yellow: "0xf0c674"
      blue: "0x81a2be"
      magenta: "0xb294bb"
      cyan: "0x8abeb7"
      white: "0xc5c8c6"

    # Bright colors
    bright:
      black: "0x969896"
      red: "0xcc6666"
      green: "0xb5bd68"
      yellow: "0xf0c674"
      blue: "0x81a2be"
      magenta: "0xb294bb"
      cyan: "0x8abeb7"
      white: "0xffffff"

    indexed_colors:
      - { index: 16, color: "0xde935f" }
      - { index: 17, color: "0xa3685a" }
      - { index: 18, color: "0x282a2e" }
      - { index: 19, color: "0x373b41" }
      - { index: 20, color: "0xb4b7b4" }
      - { index: 21, color: "0xe0e0e0" }

  tomorrow_light: &tomorrow_light
     # Default colors
     primary:
       background: '0xffffff'
       foreground: '0x4d4d4c'

     # Colors the cursor will use if `custom_cursor_colors` is true
     cursor:
       text: '0xffffff'
       cursor: '0x4d4d4c'

     # Normal colors
     normal:
       black:   '0xffffff'
       red:     '0xc82829'
       green:   '0x718c00'
       yellow:  '0xeab700'
       blue:    '0x4271ae'
       magenta: '0x8959a8'
       cyan:    '0x3e999f'
       white:   '0x4d4d4c'

     # Bright colors
     bright:
       black:   '0x8e908c'
       red:     '0xc82829'
       green:   '0x718c00'
       yellow:  '0xeab700'
       blue:    '0x4271ae'
       magenta: '0x8959a8'
       cyan:    '0x3e999f'
       white:   '0x1d1f21'

     indexed_colors:
       - { index: 16, color: '0xf5871f' }
       - { index: 17, color: '0xa3685a' }
       - { index: 18, color: '0xf2f2f2' }
       - { index: 19, color: '0xd6d6d6' }
       - { index: 20, color: '0x969896' }
       - { index: 21, color: '0x282a2e' }


colors: *tomorrow_dark
```

## config.yaml
```yml
themes:
  default:
    fg: 7
    bg: 0
    black: 0
    red: 1
    green: 2
    yellow: 3
    blue: 4
    magenta: 5
    cyan: 6
    white: 7
    orange: 16
    gray: 18
```

**Comment by max-sixty** [comment]
Thanks for the suggestion @casonadams . Mine does look much better, but it's not quite there — here's the pane view. Any ideas for what I might be doing wrong?

<img width="346" alt="image" src="https://user-images.githubusercontent.com/5635139/147452737-5001e124-7d9d-40a1-bc97-60f677a0796c.png">

**Comment by casonadams** [comment]
@max-sixty what terminal are you using?

**Comment by max-sixty** [comment]
Alacrity! On MacOS

**Comment by casonadams** [comment]
Can you share your `alacritty.yml` please and what version of `zellij` do you have?  I seem to be on `zellij 0.23.0`

**Comment by casonadams** [comment]
@max-sixty I created a nice helper script if you are at all interested [alacritty-shell](https://github.com/casonadams/alacritty-shell).  If you use `zsh` it can be installed as a plugin too.  Might be useful in switching back and forth from a light to dark color schemes in alacritty.  Anyway best of luck I am off to bed for the night.

**Comment by max-sixty** [comment]
Thanks @casonadams . I'm also on 0.23.0. 

Here's my full alacritty.yml. alacritty-shell looks great, but unfortunately I'm using fish...

Happy to make any changes you suggest. Thanks!

<details><summary>alacritty.yml</summary>

```yaml
# # Colors (One Light)
# colors:
#   primary:
#     background: "#fafafa"
#     foreground: "#383a42"
# cursor:
#   text: CellBackground
#   cursor: "#526eff" # syntax-cursor-color
# selection:
#   text: CellForeground
#   background: "#e5e5e6" # syntax-selection-color
# normal:
#   black: "#696c77" # mono-2
#   red: "#e45649" # red 1
#   green: "#50a14f"
#   yellow: "#c18401" # orange 2
#   blue: "#4078f2"
#   magenta: "#a626a4"
#   cyan: "#0184bc"
#   white: "#a0a1a7" # mono-3

# Colors (Pencil Light)
colors:
  primary:
    # @max changed to white background.
    # background: "#f1f1f1"
    background: "#ffffff"
    foreground: "#424242"

  normal:
    black: "#212121"
    red: "#c30771"
    green: "#10a778"
    yellow: "#a89c14"
    blue: "#008ec4"
    magenta: "#523c79"
    cyan: "#20a5ba"
    # @max changed to full white
    white: "#ffffff"

  bright:
    black: "#212121"
    red: "#fb007a"
    green: "#5fd7af"
    yellow: "#f3e430"
    blue: "#20bbfc"
    magenta: "#6855de"
    cyan: "#4fb8cc"
    # @max changed to full white
    white: "#ffffff"

  # dim:
  #   # black: "#131415"
  #   # red: "#864343"
  #   # green: "#777c44"
  #   # yellow: "#9e824c"
  #   # blue: "#556a7d"
  #   # magenta: "#75617b"
  #   # cyan: "#5b7d78"
  #   # white: "#828482"
  # Red cursor added by @max
  cursor:
    cursor: "#f31459"
    # text: CellBackground

selection:
  # text: CellBackground
  # background: CellForeground
  text: "#f31459"
  background: "#f31459"

cursor:
  style:
    # - ▇ Block
    # - _ Underline
    # - | Beam
    shape: Block

    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: Never
    # This seems to do nothing, even on TERM=alacritty
  vi_mode_style: Beam

font:
  normal:
    # TODO: when we have this sorted on linux
    # family: "Jetbrains Mono"
    family: JetBrainsMono Nerd Font
    # Fallback not implemented in Alacritty
    # family: "'JetBrainsMono Nerd Font','JetBrains Mono'"
    style: Regular

  size: 14

# Thin stroke font rendering (macOS only)
#
# Thin strokes are suitable for retina displays, but for non-retina screens
# it is recommended to set `use_thin_strokes` to `false`.
use_thin_strokes: true

key_bindings:
  # From my kinesis shortcuts (Kinesis -> Alacritty -> Zellij!)
  #
  # Hopefully some point we can simplify
  # this — let Zellij read the keys directly, rather than changing them to
  # something else.
  #

  - { key: RBracket, mods: Command|Shift, chars: "\x1B]" }
  - { key: LBracket, mods: Command|Shift, chars: "\x1B[" }

  # TODO: add in 26 & 27, or try this:
  # - { key: RBracket, mods: Logo|Shift, chars: "\x1B]" }
  # - { key: LBracket, mods: Logo|Shift, chars: "\x1B[" }
  # For some reason, on linux, modifier + Bracket doesn't register the key,
  # and we need to use the key numbers. But Command does work. For some *other*
  # weird reason, having these enabled on Mac Dvorak disables the second one
  # from working — I think because key 27 & 26 refer to different things, and
  # maybe one refers to the other? But the relevant keys seem to work on linux?
  #
  #
  # For Linux when using a Kinesis on dvorak.
  # Note - in dvorak, these are 27 & 24, and in querty they are 33 & 30, respectively. From:
  # alacritty --print-events | rg Bracket
  - { key: 27, mods: Command|Shift, chars: "\x1B]" }
  - { key: 26, mods: Command|Shift, chars: "\x1B[" }

  # For Zellij
  - { key: Up, mods: Shift, chars: "\ek" }
  - { key: Down, mods: Shift, chars: "\ej" }
  - { key: Left, mods: Shift, chars: "\eh" }
  - { key: Right, mods: Shift, chars: "\el" }
  # F2
  - { key: Space, mods: Control, chars: "\x1bOQ" }

  # https://github.com/fish-shell/fish-shell/issues/7440#issuecomment-719900638
  - { key: Return, mods: Alt, chars: "\e\r" }

  - {
      key: Comma,
      mods: Command,
      command:
        {
          program: "sh",
          args: ["-c", "code ~/.config/alacritty/alacritty.yml"],
        },
    }
    # For Alacritty 10
    # - { key: N, mods: Command, action: CreateNewWindow }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: Space, mods: Alt, chars: " " }
  - { key: Back, mods: Super, chars: "\x15" } # delete word/line
  - { key: Left, mods: Alt, chars: "\x1bb" } # one word left
  - { key: Right, mods: Alt, chars: "\x1bf" } # one word right
  - { key: Left, mods: Command, chars: "\x1bOH", mode: AppCursor } # Home
  - { key: Right, mods: Command, chars: "\x1bOF", mode: AppCursor } # End

  # References:
  # https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/
  - { key: PageUp, action: ScrollPageUp }
  - { key: PageUp, mode: Alt, chars: "\e[5~" }
  - { key: PageUp, mods: Shift, chars: "\e[5~" }
  - { key: PageDown, action: ScrollPageDown }
  - { key: PageDown, mode: Alt, chars: "\e[6~" }
  - { key: PageDown, mods: Shift, chars: "\e[6~" }
  - { key: Home, action: ScrollToTop }
  - { key: Home, mode: Alt, chars: "\eOH" }
  - { key: Home, mods: Shift, chars: "\e[H" }
  - { key: End, action: ScrollToBottom }
  - { key: End, mode: Alt, chars: "\eOF" }
  - { key: End, mods: Shift, chars: "\e[F" }
  - { key: Tab, mods: Alt, chars: "\e\t" }
  - { key: Tab, mods: Alt|Shift, chars: "\e\e[Z" }
  - { key: Back, chars: "\x7F" }
  - { key: Back, mods: Alt, chars: "\e\x7F" }
  - { key: Back, mods: Alt|Shift, chars: "\e\b" }
  # - { key: Space, mods: Control, chars: "\0" }
  - { key: Space, mods: Alt, chars: " " }
  - { key: Left, mods: Alt, chars: "\eb" }
  - { key: Left, mods: Alt|Shift, chars: "\e\e[D" }
  - { key: Right, mods: Alt, chars: "\ef" }
  - { key: Right, mods: Alt|Shift, chars: "\e\e[C" }
  - { key: Down, mods: Alt, chars: "\e\e[B" }
  - { key: Down, mods: Alt|Shift, chars: "\e\e[B" }
  - { key: Up, mods: Alt, chars: "\e\e[A" }
  - { key: Up, mods: Alt|Shift, chars: "\e\e[A" }
  - { key: A, mods: Alt, chars: "\ea" }
  - { key: A, mods: Alt|Shift, chars: "\eA" }
  - { key: B, mods: Alt, chars: "\eb" }
  - { key: B, mods: Alt|Shift, chars: "\eB" }
  - { key: C, mods: Alt, chars: "\ec" }
  - { key: C, mods: Alt|Shift, chars: "\eC" }
  - { key: D, mods: Alt, chars: "\ed" }
  - { key: D, mods: Alt|Shift, chars: "\eD" }
  - { key: E, mods: Alt, chars: "\ee" }
  - { key: E, mods: Alt|Shift, chars: "\eE" }
  - { key: F, mods: Alt, chars: "\ef" }
  - { key: F, mods: Alt|Shift, chars: "\eF" }
  - { key: G, mods: Alt, chars: "\eg" }
  - { key: G, mods: Alt|Shift, chars: "\eG" }
  - { key: H, mods: Alt, chars: "\eh" }
  - { key: H, mods: Alt|Shift, chars: "\eH" }
  - { key: I, mods: Alt, chars: "\ei" }
  - { key: I, mods: Alt|Shift, chars: "\eI" }
  - { key: J, mods: Alt, chars: "\ej" }
  - { key: J, mods: Alt|Shift, chars: "\eJ" }
  - { key: K, mods: Alt, chars: "\ek" }
  - { key: K, mods: Alt|Shift, chars: "\eK" }
  - { key: L, mods: Alt, chars: "\el" }
  - { key: L, mods: Alt|Shift, chars: "\eL" }
  - { key: M, mods: Alt, chars: "\em" }
  - { key: M, mods: Alt|Shift, chars: "\eM" }
  - { key: N, mods: Alt, chars: "\en" }
  - { key: N, mods: Alt|Shift, chars: "\eN" }
  - { key: O, mods: Alt, chars: "\eo" }
  - { key: O, mods: Alt|Shift, chars: "\eO" }
  - { key: P, mods: Alt, chars: "\ep" }
  - { key: P, mods: Alt|Shift, chars: "\eP" }
  - { key: Q, mods: Alt, chars: "\eq" }
  - { key: Q, mods: Alt|Shift, chars: "\eQ" }
  - { key: R, mods: Alt, chars: "\er" }
  - { key: R, mods: Alt|Shift, chars: "\eR" }
  - { key: S, mods: Alt, chars: "\es" }
  - { key: S, mods: Alt|Shift, chars: "\eS" }
  - { key: T, mods: Alt, chars: "\et" }
  - { key: T, mods: Alt|Shift, chars: "\eT" }
  - { key: U, mods: Alt, chars: "\eu" }
  - { key: U, mods: Alt|Shift, chars: "\eU" }
  - { key: V, mods: Alt, chars: "\ev" }
  - { key: V, mods: Alt|Shift, chars: "\eV" }
  - { key: W, mods: Alt, chars: "\ew" }
  - { key: W, mods: Alt|Shift, chars: "\eW" }
  - { key: X, mods: Alt, chars: "\ex" }
  - { key: X, mods: Alt|Shift, chars: "\eX" }
  - { key: Y, mods: Alt, chars: "\ey" }
  - { key: Y, mods: Alt|Shift, chars: "\eY" }
  - { key: Z, mods: Alt, chars: "\ez" }
  - { key: Z, mods: Alt|Shift, chars: "\eZ" }
  - { key: Key1, mods: Alt, chars: "\e1" }
  - { key: Key1, mods: Alt|Shift, chars: "\e!" }
  - { key: Key2, mods: Alt, chars: "\e2" }
  - { key: Key2, mods: Alt|Shift, chars: "\e#" }
  - { key: Key3, mods: Alt, chars: "\e3" }
  - { key: Key3, mods: Alt|Shift, chars: "\e#" }
  - { key: Key4, mods: Alt, chars: "\e4" }
  - { key: Key4, mods: Alt|Shift, chars: "\e$" }
  - { key: Key5, mods: Alt, chars: "\e5" }
  - { key: Key5, mods: Alt|Shift, chars: "\e%" }
  - { key: Key6, mods: Alt, chars: "\e6" }
  - { key: Key6, mods: Alt|Shift, chars: "\e^" }
  - { key: Key7, mods: Alt, chars: "\e7" }
  - { key: Key7, mods: Alt|Shift, chars: "\e&" }
  - { key: Key8, mods: Alt, chars: "\e8" }
  - { key: Key8, mods: Alt|Shift, chars: "\e*" }
  - { key: Key9, mods: Alt, chars: "\e9" }
  - { key: Key9, mods: Alt|Shift, chars: "\e(" }
  - { key: Key0, mods: Alt, chars: "\e0" }
  - { key: Key0, mods: Alt|Shift, chars: "\e)" }
  - { key: Minus, mods: Alt, chars: "\e-" }
  - { key: Minus, mods: Alt|Shift, chars: "\e_" }
  - { key: Equals, mods: Alt, chars: "\e=" }
  - { key: Equals, mods: Alt|Shift, chars: "\e+" }
  - { key: LBracket, mods: Alt, chars: "\x1B[" }
  - { key: LBracket, mods: Alt|Shift, chars: "\x1B{" }
  - { key: RBracket, mods: Alt, chars: "\x1B]" }
  - { key: RBracket, mods: Alt|Shift, chars: "\x1B}" }
  - { key: Backslash, mods: Alt, chars: "\e\\" }
  - { key: Backslash, mods: Alt|Shift, chars: "\e|" }
  - { key: Semicolon, mods: Alt, chars: "\e;" }
  - { key: Semicolon, mods: Alt|Shift, chars: "\e:" }
  - { key: Apostrophe, mods: Alt, chars: "\e'" }
  - { key: Apostrophe, mods: Alt|Shift, chars: "\e\"" }
  - { key: Comma, mods: Alt, chars: "\e," }
  - { key: Comma, mods: Alt|Shift, chars: "\e<" }
  - { key: Period, mods: Alt, chars: "\e." }
  - { key: Period, mods: Alt|Shift, chars: "\e>" }
  - { key: Slash, mods: Alt, chars: "\e/" }
  - { key: Slash, mods: Alt|Shift, chars: "\e?" }
  - { key: Grave, mods: Alt, chars: "\e`" }
  - { key: Grave, mods: Alt|Shift, chars: "\e~" }

  # - { key: F1, chars: "\x1bOP" }
  # - { key: F2, chars: "\x1bOQ" }
  # - { key: F3, chars: "\x1bOR" }
  # - { key: F4, chars: "\x1bOS" }
  # - { key: F5, chars: "\x1b[15~" }
  # - { key: F6, chars: "\x1b[17~" }
  # - { key: F7, chars: "\x1b[18~" }
  # - { key: F8, chars: "\x1b[19~" }
  # - { key: F9, chars: "\x1b[20~" }
  # - { key: F10, chars: "\x1b[21~" }
  # - { key: F11, chars: "\x1b[23~" }
  # - { key: F12, chars: "\x1b[24~" }
  #   # All from https://github.com/alacritty/alacritty/issues/2017#issuecomment-581707489
  #   # (could also use https://github.com/alacritty/alacritty/issues/62#issuecomment-347552058)

  # https://github.com/alacritty/alacritty/issues/690
  - { key: F1, mods: Shift, chars: "\x1b[1;2P" }
  - { key: F2, mods: Shift, chars: "\x1b[1;2Q" }
  - { key: F3, mods: Shift, chars: "\x1b[1;2R" }
  - { key: F4, mods: Shift, chars: "\x1b[1;2S" }
  - { key: F5, mods: Shift, chars: "\x1b[15;2~" }
  - { key: F6, mods: Shift, chars: "\x1b[17;2~" }
  - { key: F7, mods: Shift, chars: "\x1b[18;2~" }
  - { key: F8, mods: Shift, chars: "\x1b[19;2~" }
  - { key: F9, mods: Shift, chars: "\x1b[20;2~" }
  - { key: F10, mods: Shift, chars: "\x1b[21;2~" }
  - { key: F11, mods: Shift, chars: "\x1b[23;2~" }
  - { key: F12, mods: Shift, chars: "\x1b[24;2~" }
  - { key: F1, mods: Control, chars: "\x1b[1;5P" }
  - { key: F2, mods: Control, chars: "\x1b[1;5Q" }
  - { key: F3, mods: Control, chars: "\x1b[1;5R" }
  - { key: F4, mods: Control, chars: "\x1b[1;5S" }
  - { key: F5, mods: Control, chars: "\x1b[15;5~" }
  - { key: F6, mods: Control, chars: "\x1b[17;5~" }
  - { key: F7, mods: Control, chars: "\x1b[18;5~" }
  - { key: F8, mods: Control, chars: "\x1b[19;5~" }
  - { key: F9, mods: Control, chars: "\x1b[20;5~" }
  - { key: F10, mods: Control, chars: "\x1b[21;5~" }
  - { key: F11, mods: Control, chars: "\x1b[23;5~" }
  - { key: F12, mods: Control, chars: "\x1b[24;5~" }
  - { key: F1, mods: Alt, chars: "\x1b[1;6P" }
  - { key: F2, mods: Alt, chars: "\x1b[1;6Q" }
  - { key: F3, mods: Alt, chars: "\x1b[1;6R" }
  - { key: F4, mods: Alt, chars: "\x1b[1;6S" }
  - { key: F5, mods: Alt, chars: "\x1b[15;6~" }
  - { key: F6, mods: Alt, chars: "\x1b[17;6~" }
  - { key: F7, mods: Alt, chars: "\x1b[18;6~" }
  - { key: F8, mods: Alt, chars: "\x1b[19;6~" }
  - { key: F9, mods: Alt, chars: "\x1b[20;6~" }
  - { key: F10, mods: Alt, chars: "\x1b[21;6~" }
  - { key: F11, mods: Alt, chars: "\x1b[23;6~" }
  - { key: F12, mods: Alt, chars: "\x1b[24;6~" }
  - { key: F1, mods: Super, chars: "\x1b[1;3P" }
  - { key: F2, mods: Super, chars: "\x1b[1;3Q" }
  - { key: F3, mods: Super, chars: "\x1b[1;3R" }
  - { key: F4, mods: Super, chars: "\x1b[1;3S" }
  - { key: F5, mods: Super, chars: "\x1b[15;3~" }
  - { key: F6, mods: Super, chars: "\x1b[17;3~" }
  - { key: F7, mods: Super, chars: "\x1b[18;3~" }
  - { key: F8, mods: Super, chars: "\x1b[19;3~" }
  - { key: F9, mods: Super, chars: "\x1b[20;3~" }
  - { key: F10, mods: Super, chars: "\x1b[21;3~" }
  - { key: F11, mods: Super, chars: "\x1b[23;3~" }
  - { key: F12, mods: Super, chars: "\x1b[24;3~" }

alt_send_esc: false

# Window padding (changes require restart)

# Blank space added around the window in pixels. This padding is scaled
# by DPI and the specified value is always added at both opposing sides.
window:
  padding:
    x: 6
    y: 6
  decorations: none

```
</details>

**Comment by casonadams** [comment]
@max-sixty give this config a try

```
schemes:
  pencil-light: &pencil-light
    primary:
        # @max changed to white background.
        # background: "#f1f1f1"
        background: "#ffffff"
        foreground: "#424242"

    cursor:
      cursor: "#f31459"
    normal:
      black: "#212121"
      red: "#c30771"
      green: "#10a778"
      yellow: "#a89c14"
      blue: "#008ec4"
      magenta: "#523c79"
      cyan: "#20a5ba"
      # @cadams changed to dark color not white (light background this should be dark)
      white: "#222222"

    bright:
      black: "#212121"
      red: "#fb007a"
      green: "#5fd7af"
      yellow: "#f3e430"
      blue: "#20bbfc"
      magenta: "#6855de"
      cyan: "#4fb8cc"
      # @max changed to full white
      white: "#ffffff"
    indexed_colors:
      - { index: 16, color: '0xd75f00' }
      - { index: 17, color: '0x986801' }
      - { index: 18, color: '0xf0f0f1' }
      - { index: 19, color: '0xe5e5e6' }
      - { index: 20, color: '0x696c77' }
      - { index: 21, color: '0x202227' }

colors: *pencil-light
```

BTW I couldn't find pencil-light themes anywhere.  Do you mind sharing where the source came from?
