### ISSUE TITLE
Panic when running with plugin.yml

### ISSUE THREAD

**Issue by fsevenm** [zellij-org/zellij#571]
I don't really understand what happened. I compiled the plugin template successfully, but, when trying to call it with `zellij -l plugin.yml` I got the error like in the ss below. I can't even type anything on that tab but close the tab.

![image](https://user-images.githubusercontent.com/29963765/121017995-7ed5d500-c7d0-11eb-8f50-d1848bbfc688.png)

```console
❯ rustc --version
rustc 1.52.1 (9bc8c42bb 2021-05-09)

❯ cargo --version
cargo 1.52.0 (69767412a 2021-04-21)

❯ rustup --version
rustup 1.24.2 (755e2b07e 2021-05-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.52.1 (9bc8c42bb 2021-05-09)`

❯ rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
beta-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
```

Content of plugin.yml:
```yml
---
direction: Horizontal
parts:
  - direction: Vertical
    split_size:
      Fixed: 1
    plugin: tab-bar
  - direction: Vertical
    plugin: target/wasm32-wasi/debug/mode-logger.wasm
  - direction: Vertical
    split_size:
      Fixed: 2
    plugin: status-bar
```

Update:
- I follow instructionn in this https://zellij.dev/documentation/plugin-rust.html
- Even though I comment out the plugin line `plugin: target/wasm32-wasi/debug/mode-logger.wasm` in plugin.yaml, it keeps error
