### ISSUE TITLE
Split `layouts` into `full-layouts` and `tab-layouts`

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#603]
@a-kenji - what do you think of something like this?

```
direction: Horizontal
parts:
  - direction: Vertical
    split_size:
      Fixed: 1
    plugin: tab-bar
  - direction: Vertical
    tabs:
      - <layout_for_tab1> (or empty/tabname/null/some-more-intuitive-indication to just have one terminal in this tab)
      - <layout_for_tab2>
  - direction: Vertical
    split_size:
      Fixed: 2
    plugin: status-bar
```
(we'll have to validate that there's only one "tabs" section in a layout file)

_Originally posted by @imsnif in https://github.com/zellij-org/zellij/issues/551#issuecomment-865371907_

**Comment by a-kenji** [comment]
Maybe be able to specify either the tab layout in the layout itself,
or through a path to a layout, so instead of:
```
    tabs:
      - <layout_for_tab1>   
      - <layout_for_tab2> 

```
something like:
```
    tabs:
      - <path_to_layout> 
      - direction: Horizontal
        parts:
           ...
```
