### ISSUE TITLE
Add `root-directory` to the layout

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#604]
From #551,
https://github.com/zellij-org/zellij/issues/551#issue-906708819

```


---
root: ~/project1               <--- Add config param
direction: Horizontal
parts:
  - direction: Vertical
    split_size:
      Fixed: 1
    plugin: tab-bar
```
