### ISSUE TITLE
Add browser like tab navigation shortcuts to default settings.

### ISSUE THREAD

**Issue by splitcells** [zellij-org/zellij#618]
According to the description, this is an `A terminal workspace with batteries included`.
In browsers and apps like gedit it is common to switch between tabs via a keyboard shortcut.
How about adding this to the default config?

I'm currently using browser like config, and it makes tab navigation
a lot more intuitive.
```
keybinds:
    normal:
        - action: [ GoToTab: 1,]
          key: [ Alt: '1',]
        - action: [ GoToTab: 2,]
          key: [ Alt: '2',]
        - action: [ GoToTab: 3,]
          key: [ Alt: '3',]
        - action: [ GoToTab: 4,]
          key: [ Alt: '4',]
        - action: [ GoToTab: 5,]
          key: [ Alt: '5',]
        - action: [ GoToTab: 6,]
          key: [ Alt: '6',]
        - action: [ GoToTab: 7,]
          key: [ Alt: '7',]
        - action: [ GoToTab: 8,]
          key: [ Alt: '8',]
        - action: [ GoToTab: 9,]
          key: [ Alt: '9',]
```
