### ISSUE TITLE
Default to a proportionate `split_size` in `layouts`

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#619]
If no `split_size` is specified, then split proportionate to the number of 
`parts` in a split.

Eg:
```
parts:
    - direction: Horizontal
    - direction: Horizontal
    - direction: Horizontal
```
Should each have the same split size by default.
