### ISSUE TITLE
[Plugin] Status bar plugin issue when the status bar is at the top

### ISSUE THREAD

**Issue by sagittarius-a** [zellij-org/zellij#628]
# Context

I was trying to swap the position of the `status-bar` and the `tab-bar`. To be more explicit, I wanted to:

- have the status-bar at the top, with a single line only (with the overview of the current mode only, without the `Tip` section)
- have the `tab-bar` at the bottom without further changes

 
# Changes on my side

To do so, I changed the `zellij-utils/assets/layouts/default.yaml` file with the following content:

```yml
---
direction: Horizontal
parts:
  - direction: Vertical
    split_size:
      Fixed: 1
    run:
      plugin: target/wasm32-wasi/debug/status-bar.wasm
  - direction: Vertical
  - direction: Vertical
    split_size:
      Fixed: 2
    run:
      plugin: tab-bar
```

I also updated the status-bar plugin applying the following changes in order to disable the `Tip` section:
```diff
--- a/default-plugins/status-bar/src/main.rs
+++ b/default-plugins/status-bar/src/main.rs
@@ -169,6 +169,6 @@ impl ZellijPlugin for State {
                 println!("{}\u{1b}[48;5;{}m\u{1b}[0K", first_line, color);
             }
         }
-        println!("\u{1b}[m{}\u{1b}[0K", second_line);
+        // println!("\u{1b}[m{}\u{1b}[0K", second_line);
     }
 }
```

# Bug description

As a result, I have the status-bar at the top but there is a noticeable split, which was not present with the `tab-bar` plugin, and the prompt is not displayed until I redraw it by issuing a command.

![image](https://user-images.githubusercontent.com/8809698/127061499-4654579b-1e6c-480f-9cf6-22ce68140e5c.png)

# Questions

- Did I miss something in the `status-bar` plugin that directly solves the issue ?
- Is the status-bar designed to be at the bottom of the screen only ?

# Basic information

- zellij version: commit `f5734f2`
- lines: 21
- cols: 115
- alacritty version: `alacritty 0.8.0 (a1b13e68)` (in the screenshot. Bug reproduced in other terms as well)

#
Thanks
