### ISSUE TITLE
How to disable the UI?

### ISSUE THREAD

**Issue by knarkzel** [zellij-org/zellij#657]
I want to use this program and I prefer maximizing terminal space. Is it possible to disable the user interface (just like screen looks like)?

**Comment by a-kenji** [comment]
Hello @knarkzel,
if you want to not load the default plugins you can use following layout:
```
direction: Horizontal
parts:
  - direction: Vertical
```
you would start it either by calling 
```
zellij --layout--path [LAYOUT]
```
or by putting it in your `layout-dir` with the name `default.yaml`

If you want to disable the pane borders then you can either use:
```
zellij options --no-pane-frames
```
or put
```
no_pane_frames: true
```
in your config file.

**Comment by a-kenji** [comment]
@knarkzel,
I am closing this now in hopes this is answered for you!
If not please do keep reaching out!

**Comment by totikom** [comment]
Actually, this is only part on the answer. As for me, not the frames, but keybinding hints are the problem. As I've already memorized the needed keys, I no longer need them, so I would like to hide this:
![image](https://user-images.githubusercontent.com/21067774/147351543-e6769947-eb4d-45ab-957c-6f9aea6b27c0.png)

**Comment by jacksongoode** [comment]
I agree that this should be mentioned somewhere!

**Comment by a-kenji** [comment]
@totikom 
> Actually, this is only part on the answer. As for me, not the frames, but keybinding hints are the problem.

That is what my answer solved.

If you load a layout without the default plugins, then you won't load them.

> if you want to not load the default plugins you can use following layout

I personally also don't use the status bar and use the tab bar as my bottom bar, here is my layout:
```
---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
```
You can put it in the right location and have zellij autostart this layout.


@jacksongoode 
It is mentioned:
![image](https://user-images.githubusercontent.com/65275785/158535833-dd32ecdb-4985-4523-a46f-1b2767707d02.png)
https://zellij.dev/documentation/layouts.html
https://zellij.dev/documentation/layouts-templates.html

Do you have an idea how we could make it easier to find?
