### ISSUE TITLE
Dispatching keybound actions into plugins

### ISSUE THREAD

**Issue by arefem-project** [zellij-org/zellij#662]
It would be nice if plugins could handle actions dispatched from keybindings. This would enable plugins to customize Zellij's default behavior for actions.

An example use case might be a plugin that wants to keep the current directory when creating a new pane.  This plugin would need a way to handle "NewPane" actions dispatched from Zellij. The API for handling dispatched actions from inside plugins might look like this:

```rust
use zellij_tile::prelude::*;

#[derive(Default)]
struct StickyCWD {
 // ...
}

register_plugin!(StickyCWD);

impl ZellijPlugin for StickyCWD {
    fn load(&mut self) {
        subscribe(&[ EventType::Action ]);
    }

    fn update(&mut self, event: Event) {
        match event {
            Event::Action(Action::NewPane(direction)) => {
                 // TODO: Open terminal with pane direction and current directory
            }
            _ => {}
        }
}

```

While the config file would look like this:

```yaml
keybinds:
    plugins:
        sticky-cwd:
            pane:
                - action: [ NewPane: Right, ]
                  key: [ Char: 'm', ]
```

This above config would dispatch an Action::NewPane(Direction::Right) enum into the plugin when the "m" key is pressed inside the pane mode. The above presupposes that we have a way to associate the "sticky-cwd" tag with the running StickyCWD plugin.

**Comment by a-kenji** [comment]
Thanks @arefem-project for taking the time writing this issue down!
I have to agree that would be a great feature to have.

The plugin side looks good to me personally, but I am not that familiar with it.
I think it is a lot of configuration for just changing potentially one action here, but I am not sure how to make it possibly less verbose. Maybe somehow look at #661 and put these together.

**Comment by spacemaison** [comment]
Ah yeah I realize now that I was logged into the wrong account while posting this issue @a-kenji. Both #661 and #662 are me.

> I think it is a lot of configuration for just changing potentially one action here, but I am not sure how to make it possibly less verbose.

It could be reworked to go into the plugin configuration:

```yaml
plugins:
  - path: sticky-cwd.wasm
    tag: sticky-cwd
    keybinds:
       pane:
         - action: [ NewPane: Right, ]
           key: [ Char: 'm', ]
```

Honestly that pull request is already large enough that I was trying to break things into smaller chunks!
