### ISSUE TITLE
Theming affects pane contents

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#675]
The theming of zellij has an effect on pane contents, which is maybe a cool feature?
But it isn't obvious to me and I would like an option to turn it off, or it is a bug in that case
we could fix it.

**Basic information**

`zellij --version`: 0.16.0
`tput lines`: 30
`tput cols`: 120
`uname -av` or `ver`(Windows):

`nvim --version`: `NVIM v0.5.0`
`alacritty --version`: `alacritty 0.9.0`

Example config file:
```
themes:
  edge_dark_def:
    bg: [44, 46, 52]
    fg: [197, 205, 217]
    black: [62, 66, 73]
    red: [236, 114, 121]
    green: [116, 201, 128]
    yellow: [222, 185, 116]
    blue: [108, 182, 235]
    magenta: [211, 138, 234]
    cyan: [44, 46, 52]
    white: [197, 205, 217]
    orange: [232, 128, 44]
```

Relevant configuration in nvim:
```
        let g:edge_style = 'default'
        let g:edge_enable_italic = 1
        let g:edge_disable_italic_comment = 1
        let g:airline_theme = 'edge'

        colorscheme edge
```
Link to the [colorscheme](https://github.com/sainnhe/edge).

![image](https://user-images.githubusercontent.com/65275785/131370574-196e9064-5f90-4a5b-94a9-955494e557eb.png)
![image](https://user-images.githubusercontent.com/65275785/131370619-56d7f8d4-280d-41e1-a548-f2487651ab7a.png)
![image](https://user-images.githubusercontent.com/65275785/131370666-e44619e7-8268-45c0-97e4-bcf1381c961d.png)
![image](https://user-images.githubusercontent.com/65275785/131370811-167a538f-1331-4014-a046-cf16dcba6bf4.png)
[zellij.log](https://github.com/zellij-org/zellij/files/7078030/zellij.log)
[zellij-9.log](https://github.com/zellij-org/zellij/files/7078031/zellij-9.log)
