### ISSUE TITLE
Pane frames can get confused, if disabled and enabled.

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#690]
If a bordless pane loses focus, a pane frame gets drawn, if pane frames generally are enabled.

**Basic information**
`zellij --version`: 0.17.0

**Further information**
Reproduction:
* Start `zellij --layout-path [TEMPLATE]` with the following layout template:
```
---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin: tab-bar
    - direction: Vertical
      borderless: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 2
      run:
        plugin: status-bar
```

Gif:
![borderless](https://user-images.githubusercontent.com/65275785/132064664-0cf3537b-1738-4421-b473-b360e4c95a35.gif)
