### ISSUE TITLE
can't ctrl+c from alacritty terminal while using "bin/rails server"

### ISSUE THREAD

**Issue by qballer** [zellij-org/zellij#767]
Thank you for taking the time to file this issue! Please follow the instructions and fill the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

**Basic information**

`zellij --version`: 0.18.1
`tput lines`: 39
`tput cols`: 156
`uname -av` or `ver`(Windows): Darwin C02FX1QMMD6R 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`alacritty --version`: alacritty 0.9.0 (fed349a)
`rails --version`: Rails 6.1.4.1

**Further information**

Can't send Signal by using ctrl+c to process. 

The command for running is `bin/rails server` inside Rails project. 
Outside of zellij using the same setting alacritty/rails it works
Using zellij:
<img width="770" alt="Screen Shot 2021-10-05 at 15 35 10" src="https://user-images.githubusercontent.com/1002622/136023310-c3aa224d-b943-4139-b3f9-e83a7c4dc0d7.png">
Not using: 
<img width="830" alt="Screen Shot 2021-10-05 at 15 38 38" src="https://user-images.githubusercontent.com/1002622/136023957-e9c882fd-cc14-4c7a-a1b3-8746bcbe74e3.png">

**Comment by imsnif** [comment]
Thanks for the details!

A few questions:
1. Which shell are you using?
2. For us non-rails people, is there an easy way to just run this command to give it a try without setting up a project? If you could write a step-by-step guide of doing this it would be really helpful.

**Comment by qballer** [comment]
```bash
brew install ruby 
gem install rails 
rails new example-project
cd example-project
bin/rails server
# now ctrl+c
```
fish, version 3.3.1
zellij config: 

```yaml
---
keybinds:
    unbind: true
    normal:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's',]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [NewPane: ]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
    locked:
        - action: [NewPane: ]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'g',]
    resize:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'r', Char: "\n", Char: ' ',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [Quit]
          key: [Ctrl: 'q']
        - action: [Resize: Left,]
          key: [Char: 'h', Left,]
        - action: [Resize: Down,]
          key: [Char: 'j', Down,]
        - action: [Resize: Up,]
          key: [Char: 'k', Up, ]
        - action: [Resize: Right,]
          key: [Char: 'l', Right,]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
    pane:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'p', Char: "\n", Char: ' ',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [MoveFocus: Left,]
          key: [ Char: 'h', Left,]
        - action: [MoveFocus: Right,]
          key: [ Char: 'l', Right,]
        - action: [MoveFocus: Down,]
          key: [ Char: 'j', Down,]
        - action: [MoveFocus: Up,]
          key: [ Char: 'k', Up,]
        - action: [SwitchFocus,]
          key: [Char: 'p']
        - action: [NewPane: ,]
          key: [Char: 'n', Alt: 'n',]
        - action: [NewPane: Down,]
          key: [Char: 'd',]
        - action: [NewPane: Right,]
          key: [Char: 'r',]
        - action: [CloseFocus,]
          key: [Char: 'x',]
        - action: [ToggleFocusFullscreen,]
          key: [Char: 'f',]
        - action: [TogglePaneFrames,]
          key: [Char: 'z',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
    tab:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 't', Char: "\n", Char: ' ',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
          key: [Char: 'r']
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [GoToPreviousTab,]
          key: [ Char: 'h', Left, Up, Char: 'k',]
        - action: [GoToNextTab,]
          key: [ Char: 'l', Right,Down, Char: 'j']
        - action: [NewTab: ,]
          key: [ Char: 'n',]
        - action: [CloseTab,]
          key: [ Char: 'x',]
        - action: [ToggleActiveSyncTab]
          key: [Char: 's']
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [GoToTab: 1,]
          key: [ Char: '1',]
        - action: [GoToTab: 2,]
          key: [ Char: '2',]
        - action: [GoToTab: 3,]
          key: [ Char: '3',]
        - action: [GoToTab: 4,]
          key: [ Char: '4',]
        - action: [GoToTab: 5,]
          key: [ Char: '5',]
        - action: [GoToTab: 6,]
          key: [ Char: '6',]
        - action: [GoToTab: 7,]
          key: [ Char: '7',]
        - action: [GoToTab: 8,]
          key: [ Char: '8',]
        - action: [GoToTab: 9,]
          key: [ Char: '9',]
        - action: [ToggleTab]
          key: [ Char: "\t" ]
    scroll:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'r', Ctrl: 's', Char: ' ',
          Char: "\n",]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [ScrollToBottom, SwitchToMode: Normal,]
          key: [Ctrl: 'c',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [ScrollDown,]
          key: [Char: 'j', Down,]
        - action: [ScrollUp,]
          key: [Char: 'k', Up,]
        - action: [PageScrollDown,]
          key: [Ctrl: 'f', PageDown, Right, Char: 'l',]
        - action: [PageScrollUp,]
          key: [Ctrl: 'b', PageUp, Left, Char: 'h',]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
    renametab:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'r', Ctrl: 's', Char: ' ',]
        - action: [SwitchToMode: Tab,]
          key: [Char: "\n",]
        - action: [TabNameInput: [27] , SwitchToMode: Tab,]
          key: [Esc,]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
    session:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'o', Char: "\n", Char: ' ',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [Detach,]
          key: [Char: 'd',]

# Choose what to do when zellij receives SIGTERM, SIGINT, SIGQUIT or SIGHUP
# eg. when terminal window with an active zellij session is closed
# Options:
#   - detach (Default)
#   - quit
#on_force_close: quit
```
