### ISSUE TITLE
Colors from tokyonight colorsheme makes the UI unreadable and ugly 

### ISSUE THREAD

**Issue by gikari** [zellij-org/zellij#769]
When using colors from [tokyonight color scheme](https://github.com/folke/tokyonight.nvim/blob/main/extras/alacritty_tokyonight_storm.yml), the interface becomes very unpleasant and unreadable. In particular Cyan color is very bright and some text elements on it are not readable.

Screenshot:
![Screenshot_20211006_234919](https://user-images.githubusercontent.com/14205339/136281018-0e466a0d-d5a1-47c3-8e5f-48d197878e4b.png)

Config (I transformed the values from the Alacritty config above into RGB):
```yml
themes:
  default:
    bg: [36, 40, 59]
    fg: [192, 202, 245]
    black: [29, 32, 47]
    red: [247, 118, 142]
    green: [158, 206, 106]
    yellow: [224, 175, 104]
    blue: [122, 162, 247]
    magenta: [187, 154, 247]
    cyan: [125, 207, 255]
    white: [169, 177, 214]
    orange: [255, 158, 100]
```

For comparison, there is tmux with the same color scheme:
![Screenshot_20211006_235041](https://user-images.githubusercontent.com/14205339/136281217-1bbd0577-b512-4a27-b4c8-e7adef8508c9.png)

It is not as colorful, but at least it is readable.

Here is neovim:

![Screenshot_20211006_235505](https://user-images.githubusercontent.com/14205339/136281743-b9f8fcf8-6180-4ccf-aca6-28a87099d535.png)

Zellij version: 0.18.1

**Comment by imsnif** [comment]
I think this should work now (we had a bug with the cyan/gray color). Can you check?

**Comment by gikari** [comment]
Seems like the cyan is now gray. I don't know what to pick for gray color, but chose `[65, 72, 104]`.
It now looks better, indeed. However, the Ctrl + gpt... keys are still unreadable (see the screenshot):

![image](https://user-images.githubusercontent.com/14205339/148070023-4b1e1dba-8935-4ed0-a501-3258791a29d6.png)

Here is my new config just in case:
```yml
themes:
  default:
    bg: [36, 40, 59]
    fg: [192, 202, 245]
    black: [29, 32, 47]
    red: [247, 118, 142]
    green: [158, 206, 106]
    yellow: [224, 175, 104]
    blue: [122, 162, 247]
    magenta: [187, 154, 247]
    cyan: [125, 207, 255]
    white: [169, 177, 214]
    orange: [255, 158, 100]
    gray: [65, 72, 104]

```

I think the problem is that zellij tries to mix the terminal colors, that can be readable on top of each other or not, depending on color scheme. 

Color scheme authors assume, that colors, that are not foreground or background are only used on top of bg color or maybe inside the fg color. Notice, that the lower Hints pane is perfectly readable with orange and green on top of background color, for example, while the Ctrl hits is less readable: oranges are hard to distinguish and the white "Ctrl +"  is only readable because the white and gray colors are further apart, than they could (in different color scheme it could be an issue).
