### ISSUE TITLE
Feature: Add `--index` option for `attach` sub-command to choose the session indexed by provided number in the active sessions ordered creation date

### ISSUE THREAD

**Issue by ken-matsui** [zellij-org/zellij#823]
I would like to bring well integration for Alacritty as well as any other situation.

Alacritty is used with tmux frequently. Alacritty can be configured with shell and launch tmux on startup writing configuration like below:

```yaml
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - tmux a -t 0 || tmux
```

tmux has sessions using an index, so we can just put 0. Conversely, on zellij, we need to specify what session name we want to use. To give an example:

```yaml
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    # Attach the first session when it exists.
    - "ZELLIJ_SESSION=$(zellij list-sessions | head -n 1); [[ $ZELLIJ_SESSION =~ 'No active' ]] && zellij || zellij attach $ZELLIJ_SESSION"
```

Accordingly, I propose introducing a `--index` option to let zellij choose the session indexed by provided number in the active sessions ordered creation date. Thereby, we can clearly express the Alacritty config like tmux.

```yaml
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - zellij attach --index 0 || zellij
```

Moreover, zellij already has `--create` option so that we can do it briefly than tmux like below:

```yaml
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - zellij attach --index 0 --create
```

I showed an example with Alacritty, but I think this option can be leveraged in any other situation.

I'm going to submit a new PR related to this issue soon :)

### When active sessions are found

```sh
$ zellij list-sessions
psychotic-vein  # created at 3rd
ancient-advertisement  # created at 1st
eager-bread  # created at 2nd
ratty-comb  # created at 4th

$ zellij attach --index 0
Bye from Zellij!
```

Zellij will be attached to the `ancient-advertisement` session.

### When there are no sessions

```sh
$ zellij attach --index 0
No active zellij sessions found.
```

Zellij exits with error code 1.

### When there is no session indexed by provided number

```sh
$ zellij list-sessions
psychotic-vein
ancient-advertisement

$ zellij attach --index 50
No session indexed by 50 found. The following sessions are active:
0: psychotic-vein
1: ancient-advertisement
```

Zellij exits with error code 1.

### When there are no sessions with `--create` option

```sh
$ zellij attach --first 0 --create
Bye from Zellij!
```

Zellij will be attached to the session that was newly created.
