### ISSUE TITLE
Merging of layouts in the `tabs` section not correctly applied 

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#861]
`zellij --version`: 20.1.0

When running the following layout the `tab-bar can't be seen`.

```
---
tabs:
  - direction: Vertical
    parts:
      - direction: Vertical
        borderless: true
        split_size:
          Fixed: 1
        run:
          plugin:
            location: "zellij:tab-bar"
      - direction: Horizontal
        borderless: true
      - direction: Horizontal
        parts:
          - direction: Vertical
            split_size:
              Percent: 70
          - direction: Vertical
            split_size:
              Percent: 30
```

When running the following layout the `status-bar` can not be seen,
but it does leave some sort of artifacts on the `pane frame`.

```
---
tabs:
  - direction: Vertical
    parts:
      - direction: Vertical
        borderless: true
        split_size:
          Fixed: 2
        run:
          plugin:
            location: "zellij:status-bar"
      - direction: Horizontal
        borderless: true
      - direction: Horizontal
        parts:
          - direction: Vertical
            split_size:
              Percent: 70
          - direction: Vertical
            split_size:
              Percent: 30
```
![image](https://user-images.githubusercontent.com/65275785/141280374-16a80f1e-9cc0-4cec-aeb0-80acdc1829f0.png)

A temporary workaround until a fix is found could be:

```
---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
    - direction: Vertical
      body: true

tabs:
  - direction: Vertical
    parts:
      - direction: Horizontal
        borderless: true
      - direction: Horizontal
        parts:
          - direction: Vertical
            split_size:
              Percent: 70
          - direction: Vertical
            split_size:
              Percent: 30
```

But that is different behavior.
