### ISSUE TITLE
Trouble after upgrade

### ISSUE THREAD

**Issue by fedoranvar** [zellij-org/zellij#916]
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.
```
INFO   |zellij_client            | 2021-12-02 16:43:50.244 [main      ] [zellij-client/src/lib.rs:109]: Starting Zellij client! 
INFO   |zellij_server            | 2021-12-02 16:43:50.250 [main      ] [zellij-server/src/lib.rs:185]: Starting Zellij server! 
INFO   |zellij_server::wasm_vm   | 2021-12-02 16:43:50.301 [wasm      ] [zellij-server/src/wasm_vm.rs:80]: Wasm main thread starts 
INFO   |zellij_server::wasm_vm   | 2021-12-02 16:43:50.902 [wasm      ] [zellij-server/src/wasm_vm.rs:162]: wasm main thread exits 
INFO   |zellij_client            | 2021-12-02 16:43:50.902 [main      ] [zellij-client/src/lib.rs:333]: Bye from Zellij! 
```
**Basic information**

`zellij --version`: 0.21.0
`tput lines`: 67
`tput cols`: 100
`uname -av` or `ver`(Windows): Linux fedoranvar 5.10.81 #1-NixOS SMP Sun Nov 21 12:46:37 UTC 2021 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`nvim --version`:0.7 
`alacritty --version`: 0.8
**Further information**
Reproduction steps, noticeable behavior, related issues, etc

recently upgraded zellij on unstable nixos
 and noticed that my config wasn't correctly loaded
 
![image](https://user-images.githubusercontent.com/52028706/144417244-c25efee7-dc20-4134-90f3-45af7d801f24.png)

after that i've builded recent version (0.22.0) with `zellij-nix` and noticed changes in color, but still not as it should be
  
![image](https://user-images.githubusercontent.com/52028706/144417676-9f7e51c5-8f15-48fa-8f1f-847466ca1a74.png)

my config:
```yaml
no_pane_frames: true
on_force_close: detach
simplified_ui: true
default_shell: zsh
theme: default
default_mode: normal
disable_mouse_mode: false

# plugins:
#     - path: tab-bar
#       tag: tab-bar
    # - path: status-bar
    #   tag: status-bar
    # - path: strider
    #   tag: strider

themes:
  default:
    fg: [147, 155, 167]
    bg: [44, 46, 52]
    black: [62, 66, 73]
    gray: [62, 66, 73]
    red: [236, 114, 121]
    green: [216, 201, 128]
    yellow: [222, 185, 116]
    blue: [108, 182, 235]
    magenta: [211, 138, 234]
    cyan: [44, 46, 52]
    white: [197, 205, 217]
    orange: [232, 128, 44]

keybinds:
    unbind: true
    normal:
      # - action: [SwitchToMode: Locked,]
      #   key: [Ctrl: 'g',]
      # - action: [SwitchToMode: Pane,]
      #   key: [Ctrl: 'p',]
      # - action: [SwitchToMode: Resize,]
      #   key: [Ctrl: 'n',]
      - action: [SwitchToMode: Tab,]
        key: [Alt: 't',]
      # - action: [SwitchToMode: Scroll,]
      #   key: [Alt: 's',]
      # - action: [SwitchToMode: Session,]
      #   key: [Ctrl: 'o',]

      - action: [Quit,]
        key: [Alt: 'q',]
      - action: [MoveFocusOrTab: Left,]
        key: [ Alt: 'h',]
      - action: [MoveFocusOrTab: Right,]
        key: [ Alt: 'l',]
      - action: [MoveFocus: Down,]
        key: [ Alt: 'j',]
      - action: [MoveFocus: Up,]
        key: [ Alt: 'k',]
      # - action: [FocusPreviousPane,]
      #   key: [ Alt: '[',]
      # - action: [FocusNextPane,]
      #   key: [ Alt: ']',]

      - action: [ToggleFocusFullscreen,]
        key: [ Alt: 'm',]
      - action: [NewPane: Down,]
        key: [Alt: '-',]
      - action: [NewPane: Right,]
        key: [Alt: '|',]
      - action: [CloseFocus,]
        key: [Alt: 'x',]
      # - action: [CloseTab,]
      #   key: [Alt: 'X',]

      - action: [GoToTab: 1,]
        key: [ Alt: '1',]
      - action: [GoToTab: 2,]
        key: [ Alt: '2',]
      - action: [GoToTab: 3,]
        key: [ Alt: '3',]
      - action: [GoToTab: 4,]
        key: [ Alt: '4',]
      - action: [GoToTab: 5,]
        key: [ Alt: '5',]
      - action: [GoToTab: 6,]
        key: [ Alt: '6',]
      - action: [GoToTab: 7,]
        key: [ Alt: '7',]
      - action: [GoToTab: 8,]
        key: [ Alt: '8',]
      - action: [GoToTab: 9,]
        key: [ Alt: '9',]

      - action: [Detach,]
        key: [Alt: 'd',]
      - action: [Detach, Run: {cmd: session-man}]
        key: [Alt: 'D',]

      - action: [NewTab: ]
        key: [ Alt: 'N',]
      - action: [SwitchToMode: RenameTab, TabNameInput: [0]]
        key: [ Alt: 'r']

    renametab:
        - action: [SwitchToMode: Normal,]
          key: [Char: ' ',Char: "\n",]
        - action: [TabNameInput: [27] , SwitchToMode: Normal,]
          key: [Esc,]






    # locked:
    #     - action: [SwitchToMode: Normal,]
    #       key: [Esc,]
    # resize:
    #     - action: [SwitchToMode: Locked,]
    #       key: [Ctrl: 'g']
    #     - action: [SwitchToMode: Pane,]
    #       key: [Ctrl: 'p',]
    #     - action: [SwitchToMode: Tab,]
    #       key: [Ctrl: 't',]
    #     - action: [SwitchToMode: Normal,]
    #       key: [Esc,]
    #     - action: [SwitchToMode: Scroll,]
    #       key: [Ctrl: 's']
    #     - action: [SwitchToMode: Session,]
    #       key: [Ctrl: 'o',]
    #     - action: [Quit]
    #       key: [Ctrl: 'q']
    #     - action: [Resize: Left,]
    #       key: [Char: 'h', Left,]
    #     - action: [Resize: Down,]
    #       key: [Char: 'j', Down,]
    #     - action: [Resize: Up,]
    #       key: [Char: 'k', Up, ]
    #     - action: [Resize: Right,]
    #       key: [Char: 'l', Right,]
    #     - action: [NewPane: ,]
    #       key: [ Alt: 'n',]
    #     - action: [MoveFocus: Left,]
    #       key: [ Alt: 'h',]
    #     - action: [MoveFocus: Right,]
    #       key: [ Alt: 'l',]
    #     - action: [MoveFocus: Down,]
    #       key: [ Alt: 'j',]
    #     - action: [MoveFocus: Up,]
    #       key: [ Alt: 'k',]
    #     - action: [FocusPreviousPane,]
    #       key: [ Alt: '[',]
    #     - action: [FocusNextPane,]
    #       key: [ Alt: ']',]
    # pane:
    #     - action: [SwitchToMode: Locked,]
    #       key: [Ctrl: 'g']
    #     - action: [SwitchToMode: Resize,]
    #       key: [Ctrl: 'n',]
    #     - action: [SwitchToMode: Tab,]
    #       key: [Ctrl: 't',]
    #     - action: [SwitchToMode: Normal,]
    #       key: [Esc,]
    #     - action: [SwitchToMode: Scroll,]
    #       key: [Ctrl: 's']
    #     - action: [SwitchToMode: Session,]
    #       key: [Ctrl: 'o',]
    #     - action: [Quit,]
    #       key: [Ctrl: 'q',]
    #     - action: [MoveFocus: Left,]
    #       key: [ Char: 'h', Left,]
    #     - action: [MoveFocus: Right,]
    #       key: [ Char: 'l', Right,]
    #     - action: [MoveFocus: Down,]
    #       key: [ Char: 'j', Down,]
    #     - action: [MoveFocus: Up,]
    #       key: [ Char: 'k', Up,]
    #     - action: [SwitchFocus,]
    #       key: [Char: 'p']
    #     - action: [NewPane: ,]
    #       key: [Char: 'n', Alt: 'n',]
    #     - action: [NewPane: Down,]
    #       key: [Char: 'd',]
    #     - action: [NewPane: Right,]
    #       key: [Char: 'r',]
    #     - action: [CloseFocus,]
    #       key: [Char: 'x',]
    #     - action: [ToggleFocusFullscreen,]
    #       key: [Char: 'f',]
    #     - action: [TogglePaneFrames,]
    #       key: [Char: 'z',]
    #     - action: [FocusPreviousPane,]
    #       key: [ Alt: '[',]
    #     - action: [FocusNextPane,]
    #       key: [ Alt: ']',]
    #
    #     - action: [SwitchToMode: Locked,]
    #       key: [Ctrl: 'g']
    #     - action: [SwitchToMode: Pane,]
    #       key: [Ctrl: 'p',]
    #     - action: [SwitchToMode: Resize,]
    #       key: [Ctrl: 'n',]
    #     - action: [SwitchToMode: Scroll,]
    #       key: [Ctrl: 's']
    #     - action: [SwitchToMode: Session,]
    #       key: [Ctrl: 'o',]
    #     - action: [Quit,]
    #       key: [Ctrl: 'q',]
    #     - action: [FocusPreviousPane,]
    #       key: [ Alt: '[',]
    #     - action: [FocusNextPane,]
    #       key: [ Alt: ']',]
    #     - action: [GoToPreviousTab,]
    #       key: [ Char: 'h', Left, Up, Char: 'k',]
    #     - action: [GoToNextTab,]
    #       key: [ Char: 'l', Right,Down, Char: 'j']
    #     - action: [ToggleActiveSyncTab]
    #       key: [Char: 's']
    #     - action: [MoveFocus: Left,]
    #       key: [ Alt: 'h',]
    #     - action: [MoveFocus: Right,]
    #       key: [ Alt: 'l',]
    #     - action: [MoveFocus: Down,]
    #       key: [ Alt: 'j',]
    #     - action: [MoveFocus: Up,]
    #       key: [ Alt: 'k',]
    #     - action: [GoToTab: 1,]
    #       key: [ Char: '1',]
    #     - action: [GoToTab: 2,]
    #       key: [ Char: '2',]
    #     - action: [GoToTab: 3,]
    #       key: [ Char: '3',]
    #     - action: [GoToTab: 4,]
    #       key: [ Char: '4',]
    #     - action: [GoToTab: 5,]
    #       key: [ Char: '5',]
    #     - action: [GoToTab: 6,]
    #       key: [ Char: '6',]
    #     - action: [GoToTab: 7,]
    #       key: [ Char: '7',]
    #     - action: [GoToTab: 8,]
    #       key: [ Char: '8',]
    #     - action: [GoToTab: 9,]
    #       key: [ Char: '9',]
    #     - action: [ToggleTab]
    #       key: [ Char: "\t" ]
    # scroll:
    #     - action: [SwitchToMode: Normal,]
    #       key: [Esc,]
    #     - action: [SwitchToMode: Tab,]
    #       key: [Ctrl: 't',]
    #     - action: [SwitchToMode: Locked,]
    #       key: [Ctrl: 'g',]
    #     - action: [SwitchToMode: Pane,]
    #       key: [Ctrl: 'p',]
    #     - action: [SwitchToMode: Session,]
    #       key: [Ctrl: 'o',]
    #     - action: [SwitchToMode: Resize,]
    #       key: [Ctrl: 'n',]
    #     - action: [ScrollToBottom, SwitchToMode: Normal,]
    #       key: [Ctrl: 'c',]
    #     - action: [Quit,]
    #       key: [Ctrl: 'q',]
    #     - action: [ScrollDown,]
    #       key: [Char: 'j', Down,]
    #     - action: [ScrollUp,]
    #       key: [Char: 'k', Up,]
    #     - action: [PageScrollDown,]
    #       key: [Ctrl: 'f', PageDown, Right, Char: 'l',]
    #     - action: [PageScrollUp,]
    #       key: [Ctrl: 'b', PageUp, Left, Char: 'h',]
    #     - action: [NewPane: ,]
    #       key: [ Alt: 'n',]
    #     - action: [MoveFocus: Left,]
    #       key: [ Alt: 'h',]
    #     - action: [MoveFocus: Right,]
    #       key: [ Alt: 'l',]
    #     - action: [MoveFocus: Down,]
    #       key: [ Alt: 'j',]
    #     - action: [MoveFocus: Up,]
    #       key: [ Alt: 'k',]
    #     - action: [FocusPreviousPane,]
    #       key: [ Alt: '[',]
    #     - action: [FocusNextPane,]
    #       key: [ Alt: ']',]
    # renametab:
    #     - action: [SwitchToMode: Normal,]
    #       key: [Ctrl: 'r', Ctrl: 's', Char: ' ',]
    #     - action: [SwitchToMode: Tab,]
    #       key: [Char: "\n",]
    #     - action: [TabNameInput: [27] , SwitchToMode: Tab,]
    #       key: [Esc,]
    #     - action: [NewPane: ,]
    #       key: [ Alt: 'n',]
    #     - action: [MoveFocus: Left,]
    #       key: [ Alt: 'h',]
    #     - action: [MoveFocus: Right,]
    #       key: [ Alt: 'l',]
    #     - action: [MoveFocus: Down,]
    #       key: [ Alt: 'j',]
    #     - action: [MoveFocus: Up,]
    #       key: [ Alt: 'k',]
    #     - action: [FocusPreviousPane,]
    #       key: [ Alt: '[',]
    #     - action: [FocusNextPane,]
    #       key: [ Alt: ']',]
    # session:
    #     - action: [SwitchToMode: Locked,]
    #       key: [Ctrl: 'g']
    #     - action: [SwitchToMode: Resize,]
    #       key: [Ctrl: 'n',]
    #     - action: [SwitchToMode: Pane,]
    #       key: [Ctrl: 'p',]
    #     - action: [SwitchToMode: Tab,]
    #       key: [Ctrl: 't',]
    #     - action: [SwitchToMode: Normal,]
    #       key: [Esc,]
    #     - action: [SwitchToMode: Scroll,]
    #       key: [Ctrl: 's']
    #
    #     - action: [Quit,]
    #       key: [Ctrl: 'q',]
    #     - action: [Detach,]
    #       key: [Char: 'd',]


```
