### ISSUE TITLE
Alt-j cannot be remapped to Right in 0.21

### ISSUE THREAD

**Issue by lparcq** [zellij-org/zellij#923]
The following configuration that replaces the keys hjkl by vdlj (for bépo keyboard) was working in version **0.20.1**. Alt-j was correctly moving to the tab on the right. In **0.21.0**, it doesn't work and Alt-l is still bound to Right.

```
keybinds:
    normal:
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'v',]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'd',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'l',]
```
