### ISSUE TITLE
crash when unbinding keys without rebinding

### ISSUE THREAD

**Issue by valeth** [zellij-org/zellij#949]
**Basic information**

`zellij --version`: 0.22.1
`tput lines`: 43
`tput cols`: 143
`uname -av`: Linux ayano 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000 x86_64 GNU/Linux

`alacritty --version`: alacritty 0.9.0 (fed349aa)
`nu --version`: 0.41.0

**Further information**

While experimenting with the config file I noticed that Zellij crashes on every key input if either a mode or every binding is unbound.

It will not crash as soon as at least one key is rebound.

<details>
<summary>Configuration</summary>

```yaml
pane_frames: false
mouse_mode: true

keybinds:
  normal:
    - unbind: true
    # if the following two lines are commented out it will crash on input
    - action: [SwitchToMode: Locked,]
      key: [Alt: "g",]
```

</details>

The following trace is printed out on the terminal:

<details>
<summary>Output</summary>

```
Originating Thread(s):
1. stdin_handler_thread: AcceptInput

Error: thread 'input_handler' panicked at 'internal error: entered unreachable code: Unrecognized mode: Normal': zellij-utils/src/input/keybinds.rs:201
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: start_thread
  13: __GI___clone
```

</details>

[zellij.log](https://github.com/zellij-org/zellij/files/7734890/zellij.log)
