### ISSUE TITLE
Regression: Unbinding no longer works

### ISSUE THREAD

**Issue by thomaseizinger** [zellij-org/zellij#956]
**Basic information**

`zellij --version`: zellij 0.21.0
`tput lines`: 90
`tput cols`: 381
`uname -av` or `ver`(Windows): Linux thomas-thinkpad 5.10.84-1-MANJARO #1 SMP PREEMPT Wed Dec 8 09:50:30 UTC 2021 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`alacritty --version`: alacritty 0.9.0 (fed349aa)

❯ micro --version
Version: 2.0.10
Commit hash: b9763856
Compiled on August 27, 2021

**Further information**

Micro has a shortcut for quitting the editor with ctrl + q. This interferes with zellij's default for quitting.

I would like to unbind all keybindings of zellij (which used to work). However, I can't seem to get a config that actually unbinds keys. I tried the following:

```
keybinds:
    normal:
        - unbind: [ Ctrl: 'q', ]
```

```
keybinds:
	unbind: true
```

```
keybindingss:
	unbind: true
```

```
keybinds:
	unbind: [ 'all' ]
```

How do I unbind all keybindings?

**Comment by matu3ba** [comment]
Please ask a question, if you are unsure if this is a bug.
```txt
keybinds:
    normal:
        - unbind: true
    renametab:
        - unbind: true
    ...
...
```
in every mode works for me.
Your check with zellij `zellij setup --check` should indicate which config is invalid.

**Comment by thomaseizinger** [comment]
It doesn't for me:

```
❯ cat ~/.config/zellij/config.yaml
keybinds:
    normal:
        - unbind: true
❯ zellij setup --dump-config
---
# Configuration for zellij.

# In order to troubleshoot your configuration try using the following command:
# `zellij setup --check`
# It should show current config locations and features that are enabled.

keybinds:
    unbind: true
    normal:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's',]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [NewPane: ]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
```

All keybindings under `normal` are still active.

**Comment by imsnif** [comment]
Hey, sorry about the experience! I've seen this reported in a few places so I guess there's something here. @a-kenji - do you have any thoughts?

**Comment by jakobnissen** [comment]
I experienced this issue and it was solved by upgrading to v 0.22.0. Incidentally, my motivation for unbinding `Ctrl-q` was precisely so I could use micro.

**Comment by imsnif** [comment]
Aha, thanks @jakobnissen - you are right. I didn't notice the version. This should be fixed in 0.22.0. Could you give it a try @thomaseizinger ?

**Comment by thomaseizinger** [comment]
> Aha, thanks @jakobnissen - you are right. I didn't notice the version. This should be fixed in 0.22.0. Could you give it a try @thomaseizinger ?

Looking at https://manjaro.org/branch-compare/, `0.22` hasn't made it into `stable` yet but I'll report back on whether or not it is fixed once I get the update :)

Will close for now and re-open if the issue persists, thank you all!

**Comment by thomaseizinger** [comment]
> Please ask a question, if you are unsure if this is a bug.
> 
> ```
> keybinds:
>     normal:
>         - unbind: true
>     renametab:
>         - unbind: true
>     ...
> ...
> ```
> 
> in every mode works for me. Your check with zellij `zellij setup --check` should indicate which config is invalid.

So using the above config crashes for me with the following error:

```
Originating Thread(s):
1. stdin_handler_thread: AcceptInput

Error: thread 'input_handler' panicked at 'internal error: entered unreachable code: Unrecognized mode: Normal': zellij-utils/src/input/keybinds.rs:201
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: start_thread
  13: __GI___clone
❯
```

Running version `0.23.0`.

**Comment by thomaseizinger** [comment]
Ah I am now running into https://github.com/zellij-org/zellij/issues/949.

**Comment by thomaseizinger** [comment]
The original config of:

```yaml
keybinds:
    normal:
        - unbind: [ Ctrl: 'q', ]
```

works again now! Thanks all :)
